### PR TITLE
feat: add GitHub Actions for creating `Takajo` release artifacts

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Created GitHub Actions to create following Takajo release artifacts
   - takajo-2.x.x-linux.zip(takajo/mitre-attack.json)
   - takajo-2.x.x-mac.zip(takajo/mitre-attack.json)
   - takajo-2.x.x-win.zip(takajo/mitre-attack.json/pcrd64.dll)
   - README-2.x.x-English.pdf
   - README-2.x.x-Japanese.pdf

## How to use
1. Run workflow
スクリーンショット 2023-12-30 21 41 05 

2. Download artifact 
スクリーンショット 2023-12-30 21 41 25

3. Unzip artifacts
スクリーンショット 2023-12-30 22 16 26

## Test
I checked GitHub Actions in my repository and confirmed that the following zip was created.
https://github.com/fukusuket/takajo-fukusuket/actions/runs/7364252562

[release-artifact.zip](https://github.com/Yamato-Security/takajo/files/13798127/release-artifact.zip)

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
Unfortunately, mac-intel binaries cannot be created because mac-intel is not supported by GitHubActions as shown below... :(
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by fukusuket** [comment]
After some research, I found that Nim supports cross-compilation as follows :)
https://nim-lang.org/docs/nimc.html#crossminuscompilation

I tried adding the following compile options for Intel mac!
https://github.com/Yamato-Security/takajo/blob/12643d7b71095947aeb2e77ae08375e50e9af53b/.github/workflows/release.yml#L36

@YamatoSecurity 
Could you please confirm whether it works on Intel Mac?🙏 

スクリーンショット 2024-01-13 9 41 47

**Comment by YamatoSecurity** [comment]
@fukusuket That's great news! Thanks, I checked it and it works no problem.
Just one thing, could you change the `artifacts` folder to `release-binaries`? I think it will be easier to understand for non-programmers.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking!  I have changed to `release-binaries` :)

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thank you!!

**Pull request merged**
