### PR TITLE
add detection rule list

### PR DESCRIPTION
**Pull request by nishikawaakira**
#175 
@YamatoSecurity 
I've implemented it, please check back when you have time.
Screenshot 2024-09-23 at 9 35 14

### CODE REVIEW

**Comment by fukusuket** [comment]
@nishikawaakira 
One point! (The order of the Rules) Other than that OK!
- Actual: Critical -> High -> Med -> **Info** -> **Low**
- Expected: Critical -> High -> Med -> **Low** -> **Info**

**Comment by YamatoSecurity** [comment]
@nishikawaakira Thanks! Looks great, just 2 small things.

Screenshot 2024-09-23 at 13 30 37
Can you change the titles to upper case for the first letter, and lower case `alerts`?
- `critical Alerts` -> `Critical alerts`
- `high Alerts` -> `High alerts`
- `med Alerts` -> `Medium alerts` (Note: Medium instead of med)
- `low Alerts` -> `Low alerts`

Also, right now the computer names are separated by 1 space, is it possible to make it multi-line and put a return character after the computer names? I think it will be easier to read that way. If it is not possible, it might be better to separate with a comma.

**Comment by nishikawaakira** [comment]
@fukusuket Thank you for your check!
@YamatoSecurity Thank you for your feedback! I have fixed it now, so please confirm!

**Review by fukusuket — APPROVED** [review]
Thank you for quick fix! LGTM!!🚀

**Review by YamatoSecurity — APPROVED** [review]
@nishikawaakira LGTM! Thanks so much!

**Comment by nishikawaakira** [comment]
Closes #175

**Comment by nishikawaakira** [comment]
closes #175

**Pull request merged**
