### PR TITLE
feat: add `stack-processes` command

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed: #93 

### Environment
- OS: macOS Sonoma version 14.2.1
- Hayabusa v2.12.0
- Nim: 2.0.2
- nimble: 0.14.2

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### help

```
 % ./takajo
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Version: 2.3.1 Year Of The Dragon Release
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  ...
  stack-logons                   stack logons by target user, target computer, source IP address and source computer
  stack-processes                stack executed processes
  ....

Command help: takajo help <COMMAND>

Examples:
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  ...
  stack-logons -t ../hayabusa/timeline.jsonl -o logons.csv
  stack-processes -t ../hayabusa/timeline.jsonl -o processes.csv
  ...
```

```
% ./takajo stack-processes -h
Usage:
  stack-processes [REQUIRED,optional-params]
stack executed processes
Options:
  -h, --help                            print this cligen-erated help
  --help-syntax                         advanced: prepend,plurals,..
  --version           bool    false     print version
  -i, --ignoreSysmon  bool    false     exclude results when Sysmon event
  --ignoreSecurity    bool    false     exclude results when Security event
  -o=, --output=      string  ""        save results to a CSV file
  -q, --quiet         bool    false     do not display the launch banner
  -t=, --timeline=    string  REQUIRED  Hayabusa JSONL timeline (profile: any besides all-field-info*)
```

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx

```
% ./takajo stack-processes -t timeline.jsonl -q
Started the Stack Processes command

This command will stack executed processes.

Counting total lines. Please wait.

Total lines: 32378

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 32378/32378 [ 0.9s< 0.0s,  42.41k/sec]

524 | C:\Windows\System32\cmd.exe
254 | C:\Windows\System32\PING.EXE
92 | C:\Windows\System32\svchost.exe
87 | C:\Windows\System32\whoami.exe
87 | C:\Windows\System32\rundll32.exe
84 | C:\Windows\System32\reg.exe
83 | C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
64 | C:\Windows\System32\calc.exe
57 | C:\Windows\System32\inetsrv\appcmd.exe
,,,
```

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx (-o)

```
% ./takajo stack-processes -t timeline.jsonl -q -o stack-process.csv
Started the Stack Processes command

This command will stack executed processes.

Counting total lines. Please wait.

Total lines: 32378

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 32378/32378 [ 1.0s< 0.0s,  37.21k/sec]


Saved file: stack-process.csv (9.28 KB)

Elapsed time: 0 hours, 0 minutes, 1 seconds

fukusuke@fukusukenoMacBook-Air hayabusa-2.12.0-all-platforms % head stack-process.csv
Count,Processes
524,C:\Windows\System32\cmd.exe
254,C:\Windows\System32\PING.EXE
92,C:\Windows\System32\svchost.exe
87,C:\Windows\System32\whoami.exe
87,C:\Windows\System32\rundll32.exe
84,C:\Windows\System32\reg.exe
83,C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
64,C:\Windows\System32\calc.exe
57,C:\Windows\System32\inetsrv\appcmd.exe
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much!

**Pull request merged**
