### PR TITLE
Update GitHub Actions setup-nim-action@v2

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
Version 2 of setup-nim-actions has been released, so I updated it.
https://github.com/jiro4989/setup-nim-action?tab=readme-ov-file#v2-version-was-released-tada

#### Integration-Test
- https://github.com/Yamato-Security/takajo/actions/runs/10730617246

#### Takajo Release Automation
- https://github.com/Yamato-Security/takajo/actions/runs/10730557733

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks! Checks seem to be failing for some reason.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Sorry! I fixed it.

**Comment by fukusuket** [comment]
I confirmed actions done successfully as follows.
- https://github.com/Yamato-Security/takajo/actions/runs/10732314499
- https://github.com/Yamato-Security/takajo/actions/runs/10732313182
- https://github.com/Yamato-Security/takajo/actions/runs/10732301667

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thank you!

**Pull request merged**
