### PR TITLE
feat: add `extract-ttps` command

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- feat: #76
- added `extract-ttps` command
- creates JSON in a format that can be imported into MITRE ATT&CK Navigator
example:
```json
{
  "name": "Hayabusa detection result heatmap",
  "versions": {
    "attack": "14",
    "navigator": "4.9.1",
    "layer": "4.5"
  },
  "domain": "enterprise-attack",
  "description": "Hayabusa detection result heatmap",
  "techniques": [
    {
      "color": "#fd8d3c",
      "techniqueID": "T1070.006"
    },
    {
      "color": "#fd8d3c",
      "techniqueID": "T1098"
    }
  ]
}
```

### Environment
- OS: macOS Sonoma version 14.0
- Hayabusa v2.12.0-dev
- Nim: 2.0.0

#### hayabusa-sample-evtx's result
```
% ./takajo extract-ttps -t out.jsonl -q
Started the Extract TTPs command.
This command extracts TTPs and creates JSON in a format that can be imported into MITRE ATT&CK Navigator.

Counting total lines. Please wait.
Total lines: 32287

100%|█████████████████████████| 32287/32287 [ 1.0s< 0.0s,  36.74k/sec]

Saved file: mitre-attack-navigator.json (890.25 KB)

Elapsed time: 0 hours, 0 minutes, 1 seconds
```
スクリーンショット 2023-12-17 4 04 55

#### help message
```
fukusuke@fukusukenoAir hayabusa-2.11.0-all-platforms % ./takajo
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Version: 2.2.0 Nasi Lemak Release
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  extract-ttps                   extracts TTPs and creates JSON in a format that can be imported into MITRE ATT&CK Navigator
  list-domains                   create a list of unique domains to be used with vt-domain-lookup
  list-hashes                    create a list of process hashes to be used with vt-hash-lookup
  list-ip-addresses              create a list of unique target and/or source IP addresses to be used with vt-ip-lookup
  list-undetected-evtx           create a list of undetected evtx files
  list-unused-rules              create a list of unused sigma rules
  split-csv-timeline             split up a large CSV file into smaller ones based on the computer name
  split-json-timeline            split up a large JSONL timeline into smaller ones based on the computer name
  stack-logons                   stack logons by target user, target computer, source IP address and source computer
  sysmon-process-tree            output the process tree of a certain process
  timeline-logon                 create a CSV timeline of logon events
  timeline-partition-diagnostic  create a CSV timeline of partition diagnostic events
  timeline-suspicious-processes  create a CSV timeline of suspicious processes
  vt-domain-lookup               look up a list of domains on VirusTotal
  vt-hash-lookup                 look up a list of hashes on VirusTotal
  vt-ip-lookup                   look up a list of IP addresses on VirusTotal

Command help: takajo help <COMMAND>

Examples:
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  extract-ttps -t ../hayabusa/timeline.jsonl -o mitre-attack-navigator.json
  list-domains -t ../hayabusa/timeline.jsonl -o domains.txt
  list-hashes -t ../hayabusa/case-1.jsonl -o case-1
  list-ip-addresses -t ../hayabusa/timeline.jsonl -o ipAddresses.txt
  list-undetected-evtx -t ../hayabusa/timeline.csv -e ../hayabusa-sample-evtx
  list-unused-rules -t ../hayabusa/timeline.csv -r ../hayabusa/rules
  split-csv-timeline -t ../hayabusa/timeline.csv [--makeMultiline] -o case-1-csv
  split-json-timeline -t ../hayabusa/timeline.jsonl -o case-1-json
  stack-logons -t ../hayabusa/timeline.jsonl -o logons.csv
  sysmon-process-tree -t ../hayabusa/timeline.jsonl -p <Process GUID> [-o process-tree.txt]
  timeline-logon -t ../hayabusa/timeline.jsonl -o logon-timeline.csv
  timeline-partition-diagnostic -t ../hayabusa/timeline.jsonl -o partition-diagnostic-timeline.csv
  timeline-suspicious-processes -t ../hayabusa/timeline.jsonl [--level medium] [-o suspicious-processes.csv]
  vt-domain-lookup  -a <API-KEY> --domainList domains.txt -r 1000 -o results.csv --jsonOutput responses.json
  vt-hash-lookup -a <API-KEY> --hashList case-1-MD5-hashes.txt -r 1000 -o results.csv --jsonOutput responses.json
  vt-ip-lookup -a <API-KEY> --ipList ipAddresses.txt -r 1000 -o results.csv --jsonOutput responses.json

```

### CODE REVIEW

**Comment by fukusuket** [comment]
@YamatoSecurity  @hitenkoku 
I tried implementing the command! What do you think about the command name and the content displayed in Navigator?
I would appreciate it if you could check it out when you have time🙏

**Comment by YamatoSecurity** [comment]
@fukusuket Wow! Thanks for the super fast PR! I will check it out.

**Comment by fukusuket** [comment]
#### apt29 day2's result
スクリーンショット 2023-12-17 21 34 26

**Comment by YamatoSecurity** [comment]
@fukusuket Looks great! I changed the command name to `ttp-visualize` because I want to add 1-2 more `ttp` commands. Can you add a kind of error checking so that if the user does not specify a hayabusa profile with `%MitreTactics%` that it gives the error message `No MITRE tactics were found in the Hayabusa results. Please run your Hayabusa scan with a profile that includes the %MitreTactics% field. (ex: -p verbose)` ?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for updating cmd and review :)
I added to output the following message when the profiles do not match (Strictly speaking, when there is no output of %MitreTags% even if the profiles match).
```
% ./takajo ttp-visualize -t 2.json -q
Started the TTP Visualize command.
This command extracts TTPs and creates a JSON file to visualize in MITRE ATT&CK Navigator.

Counting total lines. Please wait.
Total lines: 32287

100%|█████████████████████████| 32287/32287 [ 0.9s< 0.0s,  43.17k/sec]

No MITRE tags were found in the Hayabusa results.
Please run your Hayabusa scan with a profile that includes the %MitreTags% field. (ex: -p verbose)
```

**Review by hitenkoku — APPROVED** [review]
LGTM

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Thanks so much! LGTM!

**Pull request merged**
