### PR TITLE
feat: add `extract-credentials` command

### LINKED ISSUE #188: `extract-credentials` command
I'd like to create a command that tries to identify commands that were entered that contain usernames or passwords. Similar to what is explained here: https://practicalsecurityanalytics.com/extracting-credentials-from-windows-logs/
There is a risk that administrators will enter plaintext username and passwords into the command line which gets logged in 4688 events and sysmon 1 events. Attackers may abuse this for offensive purposes as described in the article, so it is important for blue teams as well to understand if these plaintext passwords are being leaked in command line option logging. (If the blue team finds credentials being logged, they can inform the user to change their password/API key and warn them of the risks)

We should also include a regular expression check to look for API keys being leaked in the event logs as well.

Output to the terminal can be a table with the following information: `Timestamp, Computer, Event (Sec-4688 or Sysmon 1), Username, Password, API Key, Commandline` or output to a CSV file.

@fukusuket Could I ask you to do this one?

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #188 
- Extract the password from the following command line
  - wmic
  - schtasks
  - net user
  - psexec

## help
```
% ./takajo
┏━━━━┳━━━┳┓┏━┳━━━┓ ┏┳━━━┓
┃┏┓┏┓┃┏━┓┃┃┃┏┫┏━┓┃ ┃┃┏━┓┃
┗┛┃┃┗┫┃ ┃┃┗┛┛┃┃ ┃┃ ┃┃┃ ┃┃
  ┃┃ ┃┗━┛┃┏┓┓┃┗━┛┣┓┃┃┃ ┃┃
  ┃┃ ┃┏━┓┃┃┃┗┫┏━┓┃┗┛┃┗━┛┃
  ┗┛ ┗┛ ┗┻┛┗━┻┛ ┗┻━━┻━━━┛
  by Yamato Security

Version: 2.7.0 Dev Build
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  automagic                      automatically executes as many commands as possible and output results to a new folder
  extract-credentials            extract credentials from the timeline
...
Examples:
  automagic -t ../hayabusa/timeline.jsonl [--level low] [--displayTable] -o case-1
  extract-credentials -t ../hayabusa/timeline.jsonl [--skipProgressBar] -o credentials.csv
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low]  [--skipProgressBar] -o scriptblock-logs
...
```

## terminal output
I checked https://github.com/Yamato-Security/takajo/issues/188#issuecomment-2381252863 commands. (I have not been able to confirm this because the wmic command line was not recorded in my environment...)
```
% ./takajo extract-credentials -t timeline.jsonl -q
Started the extract-credentials command

This command extracts credentials from command lines in Sysmon and Security event logs.

Counting total lines. Please wait.

File: timeline.jsonl (16.35 KB)
Total lines: 20

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 20/20 [ 0.0s< 0.0s,  43.31k/sec]

┌────────────────────────────────┬──────────┬──────────┬────────────┬──────────────┬─────────┬────────────────────────────────────────────────┐
│ Timestamp                      │ Computer │ Event    │ User       │ Password     │ API Key │ Cmdline                                        │
├────────────────────────────────┼──────────┼──────────┼────────────┼──────────────┼─────────┼────────────────────────────────────────────────┤
│ 2024-09-30 07:45:32.793 +09:00 │ win10    │ Sysmon-1 │ vagrant    │ vagrant      │ N/A     │ schtasks /Create /S dc /U vagrant /P vagrant   │
│                                │          │          │            │              │         │ /SC DAILY /TN MyScheculeTask /TR               │
│                                │          │          │            │              │         │ C:/Path/To/MyScript.vbs /ST 14:00              │
├────────────────────────────────┼──────────┼──────────┼────────────┼──────────────┼─────────┼────────────────────────────────────────────────┤
│ 2024-09-30 07:45:46.608 +09:00 │ win10    │ Sysmon-1 │ testuser   │ Password!#@$ │ N/A     │ net user testuser Password!#@$ /add            │
├────────────────────────────────┼──────────┼──────────┼────────────┼──────────────┼─────────┼────────────────────────────────────────────────┤
│ 2024-09-30 07:46:09.193 +09:00 │ win10    │ Sysmon-1 │ vagrant@dc │ vagrant      │ N/A     │ psexec \\dc -u vagrant@dc -p vagrant           │
│                                │          │          │            │              │         │ systeminfo                                     │
└────────────────────────────────┴──────────┴──────────┴────────────┴──────────────┴─────────┴────────────────────────────────────────────────┘


Elapsed time: 0 hours, 0 minutes, 0 seconds
```

## csv output
I checked https://github.com/Yamato-Security/takajo/issues/188#issuecomment-2381252863 commands. (I have not been able to confirm this because the wmic command line was not recorded in my environment...)
```
% ./takajo extract-credentials -t timeline.jsonl -q -o credentials.csv
Started the extract-credentials command

This command extracts credentials from command lines in Sysmon and Security event logs.

Counting total lines. Please wait.

File: timeline.jsonl (16.35 KB)
Total lines: 20

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 20/20 [ 0.0s< 0.0s,  43.55k/sec]

Saved results to credentials.csv (458 Bytes)

Elapsed time: 0 hours, 0 minutes, 0 seconds

fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm % cat credentials.csv
Timestamp,Computer,Event,User,Password,API Key,Cmdline
2024-09-30 07:45:32.793 +09:00,win10,Sysmon-1,vagrant,vagrant,N/A,schtasks /Create /S dc /U vagrant /P vagrant /SC DAILY /TN MyScheculeTask /TR C:/Path/To/MyScript.vbs /ST 14:00
2024-09-30 07:45:46.608 +09:00,win10,Sysmon-1,testuser,Password!#@$,N/A,net user testuser Password!#@$ /add
2024-09-30 07:46:09.193 +09:00,win10,Sysmon-1,vagrant@dc,vagrant,N/A,psexec \\dc -u vagrant@dc -p vagrant systeminfo
```

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
@YamatoSecurity 
I have implemented the password extraction process from the commands in the article! Please let me know if there are other commands that can be extracted🙏

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks! It is working good for the username and password credentials but seems that the API extraction is not implemented? I think I need to take some time and look at the different scenarios where an API key might be recorded so in the meantime could you remove the column and parts regarding API keys?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you for checking :) I removed API key column!💪
```
% ./takajo extract-credentials -t timeline.jsonl -q
Started the extract-credentials command

This command extracts credentials from command lines in Sysmon and Security event logs.

Counting total lines. Please wait.

File: timeline.jsonl (16.35 KB)
Total lines: 20

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 20/20 [ 0.0s< 0.0s,  60.26k/sec]

┌────────────────────────────────┬──────────┬──────────┬────────────┬──────────────┬──────────────────────────────────────────────────────────┐
│ Timestamp                      │ Computer │ Event    │ User       │ Password     │ Cmdline                                                  │
├────────────────────────────────┼──────────┼──────────┼────────────┼──────────────┼──────────────────────────────────────────────────────────┤
│ 2024-09-30 07:45:32.793 +09:00 │ win10    │ Sysmon-1 │ vagrant    │ vagrant      │ schtasks /Create /S dc /U vagrant /P vagrant /SC DAILY   │
│                                │          │          │            │              │ /TN MyScheculeTask /TR C:/Path/To/MyScript.vbs /ST 14:00 │
├────────────────────────────────┼──────────┼──────────┼────────────┼──────────────┼──────────────────────────────────────────────────────────┤
│ 2024-09-30 07:45:46.608 +09:00 │ win10    │ Sysmon-1 │ testuser   │ Password!#@$ │ net user testuser Password!#@$ /add                      │
├────────────────────────────────┼──────────┼──────────┼────────────┼──────────────┼──────────────────────────────────────────────────────────┤
│ 2024-09-30 07:46:09.193 +09:00 │ win10    │ Sysmon-1 │ vagrant@dc │ vagrant      │ psexec \\dc -u vagrant@dc -p vagrant systeminfo          │
└────────────────────────────────┴──────────┴──────────┴────────────┴──────────────┴──────────────────────────────────────────────────────────┘


Elapsed time: 0 hours, 0 minutes, 0 seconds

fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm % ./takajo extract-credentials -t timeline.jsonl -q -o credentials.csv
Started the extract-credentials command

This command extracts credentials from command lines in Sysmon and Security event logs.

Counting total lines. Please wait.

File: timeline.jsonl (16.35 KB)
Total lines: 20

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 20/20 [ 0.0s< 0.0s,  60.41k/sec]

Saved results to credentials.csv (438 Bytes)

Elapsed time: 0 hours, 0 minutes, 0 seconds

fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm % cat credentials.csv
Timestamp,Computer,Event,User,Password,Cmdline
2024-09-30 07:45:32.793 +09:00,win10,Sysmon-1,vagrant,vagrant,schtasks /Create /S dc /U vagrant /P vagrant /SC DAILY /TN MyScheculeTask /TR C:/Path/To/MyScript.vbs /ST 14:00
2024-09-30 07:45:46.608 +09:00,win10,Sysmon-1,testuser,Password!#@$,net user testuser Password!#@$ /add
2024-09-30 07:46:09.193 +09:00,win10,Sysmon-1,vagrant@dc,vagrant,psexec \\dc -u vagrant@dc -p vagrant systeminfo
fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm %
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Thanks so much! LGTM!

**Pull request merged**
