### PR TITLE
fix #179 Create a Computer Summary page

### LINKED ISSUE #179: Create a `Computer Summary` page
Now, there is no `Computer Summary` page.

I would like to add the following table:

| Computer  | Critical Alerts | High Alerts | Medium Alerts | Low Alerts | Informational Alerts |
|-----------|-----------------|-------------|---------------|------------|----------------------|
| ComputerA | 30              | 100         | 50            | 3000       | 50000                |
| ComputerB | 20              | 50          | 30            | 50         | 60000                |
| ComputerC | 10              | 10          | 10            | 10         | 534                  |

Note: the order is in the order of the most number of alerts for the highest category. So if one computer has 1 critical alerts and no critical alerts for the other computers, then it will be ranked highest. If there are no critical alerts, then the computer with the most high alerts will be ranked the highest, etc...

If it is possible to color the numbers or spaces Red for critical, orange for high, yellow for medium, etc... then I think it would look nicer.

### PR DESCRIPTION
**Pull request by nishikawaakira**
#179 is now fix. Please check
Screenshot 2024-09-07 at 11 08 07

### CODE REVIEW

**Review by fukusuket — APPROVED** [review]
I confirmed `Computer Summary` created :) LGTM!!🚀

**Comment by YamatoSecurity** [comment]
@nishikawaakira Thanks so much! Looks good! Just one question, how are you sorting the computers? Shouldn't DESKTOP-CNG7416 be above MyComputer because it has 1 high alert but MyComputer does not have any critical or high alerts?

**Comment by nishikawaakira** [comment]
@YamatoSecurity 
The sorting was only done by criticality, so it has been corrected to sort by all severities.
Screenshot 2024-09-08 at 8 32 02

**Review by YamatoSecurity — APPROVED** [review]
@nishikawaakira LGTM! Thanks so much!

**Pull request merged**
