### PR TITLE
feat: add `stack-cmdlines`

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed: #94 

### Environment
- OS: macOS Sonoma version 14.2.1
- Hayabusa v2.12.0
- Nim: 2.0.2
- nimble: 0.14.2

The stack command has almost duplicate code, so we plan to refactor it all together in #99 ...
I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### help
```
% ./takajo
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Version: 2.4.0 Dev Build
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  ...
  stack-cmdlines                 stack executed command lines
  stack-logons                   stack logons by target user, target computer, source IP address and source computer
  stack-processes                stack executed processes
  sysmon-process-tree            output the process tree of a certain process
  ...

Command help: takajo help <COMMAND>

Examples:
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  ...
  stack-cmdlines -t ../hayabusa/timeline.jsonl -o cmdlines.csv
  stack-logons -t ../hayabusa/timeline.jsonl -o logons.csv
  stack-processes -t ../hayabusa/timeline.jsonl -o processes.csv
  sysmon-process-tree -t ../hayabusa/timeline.jsonl -p <Process GUID> [-o process-tree.txt]
  ...
```

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx

```
 % ./takajo stack-cmdlines -t timeline.jsonl -o cmdlines.csv -q
Started the Stack Cmdlines command

This command will stack executed command lines.

Counting total lines. Please wait.

Total lines: 32371

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 32371/32371 [ 0.6s< 0.0s,  64.82k/sec]


Saved file: cmdlines.csv (91.06 KB)

Elapsed time: 0 hours, 0 minutes, 0 seconds

fukusuke@fukusukenoMacBook-Air hayabusa-2.13.0-mac % head cmdlines.csv
Count,Cmdlines
51,"C:\Windows\system32\cmd.exe" /c"
45,whoami
45,calc.exe
41,"C:\Windows\system32\cmd.exe"
27,cmd.exe
22,timeout 5
18,rundll32 windowscoredeviceinfo.dll,CreateBackdoor
15,c:\Windows\System32\cmd.exe
15,UI0Detect.exe 224
```

```
% cat timeline.jsonl | jq 'select(.EventID==1 and .Channel=="Sysmon")| .Details.Cmdline' -r | sort | uniq -c | sort -rn | head
  51 "C:\Windows\system32\cmd.exe" /c"
  45 whoami
  45 calc.exe
  41 "C:\Windows\system32\cmd.exe"
  27 cmd.exe
  22 timeout 5
  18 rundll32 windowscoredeviceinfo.dll,CreateBackdoor
  15 c:\Windows\System32\cmd.exe
  15 UI0Detect.exe 224
  14 utilman.exe /debug
```

**Review by hitenkoku — APPROVED** [review]
@fukusuket  Thanks for your pull request.
LGTM.

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much!

**Pull request merged**
