### PR TITLE
fix #177 Allow filtering on the Chart by Rules

### LINKED ISSUE #177: Allow filtering on the Chart by Rules
Under the `Detection Rule List` in the Computer Summary, it would be nice to be able to filter on rules. 

Screenshot 2024-08-30 at 09 26 22

So between `Detection Rule List` and the `ALERT TITLE` table, I want to add 2 links:
```
Include all rules
Exclude all rules
```

`Include all rules` will mark of the rules checked. `Exclude all rules` will uncheck all rules and make the table blank.

To the left of `ALERT TITLE`, I want to add another column called `INCLUDE?` which will contain checkboxes (if possible)

The user can then check or uncheck the rules which will update the chart above.

@nishikawaakira Is this possible to do with static pages? or will we need the dynamic web server for this?

### PR DESCRIPTION
**Pull request by nishikawaakira**
Allows filtering by rules. But you need click search button.
スクリーンショット 2024-10-20 16 35 41

### CODE REVIEW

**Review by fukusuket — APPROVED** [review]
I  have confirmed the filtering works with the binaries in the following link! LGTM!!🚀
- https://github.com/Yamato-Security/takajo/actions/runs/11430649377

**Comment by YamatoSecurity** [comment]
@nishikawaakira Thanks so much!
I cleared all the rules and hit "Search" but the results stay the same in the graph.
Screenshot 2024-10-21 at 15 42 40

Do I need to do something else?

**Comment by nishikawaakira** [comment]
@YamatoSecurity 
I assumed that at least one would be checked because I would lose data if all were cleared.

**Comment by nishikawaakira** [comment]
If there is any reason you want to display 0 cases, implement it that way!

**Comment by YamatoSecurity** [comment]
@nishikawaakira That makes sense! Maybe there is 阿呆 like me that will think that it doesn't work when trying to see the graph without any rules enabled. So could you update the graph blank? or maybe do some kind of pop-up with an error message saying "No rules are enabled."
Whichever one you think is better.

**Comment by nishikawaakira** [comment]
@YamatoSecurity Thank you for confirming! Fixed error message “No rules are enabled.”

**Review by YamatoSecurity — APPROVED** [review]
@nishikawaakira LGTM! Thank you!!

**Pull request merged**
