### PR TITLE
feat: add `ttp-summary` command

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- feat: #78 

#### 1. create mitre-attack.json
```
pip install requests
pip install beautifulsoup4
git clone https://github.com/Yamato-Security/takajo.git
cd takajo
python3 get-miter-attack.py
## then mitre-attack.json will be output current directory.
```

#### 2. run takajo
```
nimble build -d:release --threads:on
./takajo ttp-summary -t timienline.jsonl
```

### Environment
- OS: macOS Sonoma version 14.0
- Hayabusa v2.12.0-dev
- Nim: 2.0.0

### Test(Console output)
スクリーンショット 2023-12-21 9 35 34

### Test(CSV output)
```csv
Computer,Tactic,Technique,Sub-Technique,Count
-,08. Credential Access,Brute Force,Password Spraying,1
DESKTOP-JR78RLP,07. Defense Evasion,Impair Defenses,Disable Windows Event Logging,3
DESKTOP-JR78RLP,07. Defense Evasion,Indicator Removal,Clear Windows Event Logs,1
DESKTOP-M5SN04R,10. Lateral Movement,Remote Services,SMB/Windows Admin Shares,2
IE10Win7,04. Execution,System Services,Service Execution,3561
IE10Win7,05. Persistence,Create Account,Local Account,24
IE10Win7,06. Privilege Escalation,Account Manipulation,-,8
IE10Win7,06. Privilege Escalation,Create or Modify System Process,Windows Service,2
IE10Win7,07. Defense Evasion,Access Token Manipulation,Create Process with Token,69
IE10Win7,07. Defense Evasion,Access Token Manipulation,Token Impersonation/Theft,5
IE10Win7,07. Defense Evasion,Command and Scripting Interpreter,PowerShell,5
IE10Win7,07. Defense Evasion,Deobfuscate/Decode Files or Information,-,223
IE10Win7,07. Defense Evasion,Impair Defenses,Disable Windows Event Logging,18
IE10Win7,07. Defense Evasion,Indicator Removal,Clear Windows Event Logs,12
IE10Win7,07. Defense Evasion,Indicator Removal,Timestomp,7
IE10Win7,07. Defense Evasion,Obfuscated Files or Information,-,1
IE10Win7,07. Defense Evasion,Obfuscated Files or Information,Compile After Delivery,30
IE10Win7,07. Defense Evasion,System Binary Proxy Execution,-,54
IE10Win7,07. Defense Evasion,System Binary Proxy Execution,Rundll32,6
```

### Test(help)

```
fukusuke@fukusukenoAir hayabusa-2.11.0-all-platforms % ./takajo
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Version: 2.3.0 SECCON Christmas Release
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  list-domains                   create a list of unique domains to be used with vt-domain-lookup
  list-hashes                    create a list of process hashes to be used with vt-hash-lookup
  list-ip-addresses              create a list of unique target and/or source IP addresses to be used with vt-ip-lookup
  list-undetected-evtx           create a list of undetected evtx files
  list-unused-rules              create a list of unused sigma rules
  split-csv-timeline             split up a large CSV file into smaller ones based on the computer name
  split-json-timeline            split up a large JSONL timeline into smaller ones based on the computer name
  stack-logons                   stack logons by target user, target computer, source IP address and source computer
  sysmon-process-tree            output the process tree of a certain process
  timeline-logon                 create a CSV timeline of logon events
  timeline-partition-diagnostic  create a CSV timeline of partition diagnostic events
  timeline-suspicious-processes  create a CSV timeline of suspicious processes
  ttp-summary                    TODO
  ttp-visualize                  extract TTPs and create a JSON file to visualize in MITRE ATT&CK Navigator
  vt-domain-lookup               look up a list of domains on VirusTotal
  vt-hash-lookup                 look up a list of hashes on VirusTotal
  vt-ip-lookup                   look up a list of IP addresses on VirusTotal

Command help: takajo help <COMMAND>

Examples:
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  list-domains -t ../hayabusa/timeline.jsonl -o domains.txt
  list-hashes -t ../hayabusa/case-1.jsonl -o case-1
  list-ip-addresses -t ../hayabusa/timeline.jsonl -o ipAddresses.txt
  list-undetected-evtx -t ../hayabusa/timeline.csv -e ../hayabusa-sample-evtx
  list-unused-rules -t ../hayabusa/timeline.csv -r ../hayabusa/rules
  split-csv-timeline -t ../hayabusa/timeline.csv [--makeMultiline] -o case-1-csv
  split-json-timeline -t ../hayabusa/timeline.jsonl -o case-1-json
  stack-logons -t ../hayabusa/timeline.jsonl -o logons.csv
  sysmon-process-tree -t ../hayabusa/timeline.jsonl -p <Process GUID> [-o process-tree.txt]
  timeline-logon -t ../hayabusa/timeline.jsonl -o logon-timeline.csv
  timeline-partition-diagnostic -t ../hayabusa/timeline.jsonl -o partition-diagnostic-timeline.csv
  timeline-suspicious-processes -t ../hayabusa/timeline.jsonl [--level medium] [-o suspicious-processes.csv]
  ttp-visualize -t ../hayabusa/timeline.jsonl -o mitre-attack-navigator.json
  ttp-summary -t ../hayabusa/timeline.jsonl -o ttp-summary.csv
  vt-domain-lookup  -a <API-KEY> --domainList domains.txt -r 1000 -o results.csv --jsonOutput responses.json
  vt-hash-lookup -a <API-KEY> --hashList case-1-MD5-hashes.txt -r 1000 -o results.csv --jsonOutput responses.json
  vt-ip-lookup -a <API-KEY> --ipList ipAddresses.txt -r 1000 -o results.csv --jsonOutput responses.json
```

### CODE REVIEW

**Comment by fukusuket** [comment]
@YamatoSecurity 
I created a prototype!(If there seems to be no functional problem, I'll do some more testing) what do you think? 🤔
I haven't created Github Actions yet, but I'm thinking of creating one as a separate PR.

I also have a help message as a `TODO`, but I would appreciate it if you could change it in English🙏

**Comment by fukusuket** [comment]
### Test(apt29)
スクリーンショット 2023-12-21 12 11 14

**Comment by YamatoSecurity** [comment]
@fukusuket I checked it. Looks great! Let's merge it as it is. Thinking over it, I don't think we need to make it a github action like for rules as there are only updates in TTPs when a new version of ATT&CK comes out so we can update this periodically (once or twice a year?) and make sure the output is correct before updating the local file.

**Review by YamatoSecurity — APPROVED** [review]
LGTM!

**Review by hitenkoku — APPROVED** [review]
LGTM

**Comment by fukusuket** [comment]
Test(command prompt)

cmd

**Pull request merged**
