### PR TITLE
implement webserver first commit

### PR DESCRIPTION
**Pull request by nishikawaakira**
Web Server functionality has been implemented.
This allows dynamic searches in the GUI.
It also makes links to rules refer to the repository.

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
@nishikawaakira 
I got an error that `common.js` is missing, am I missing something in my procedure?🤔
(I copied the `templates` folder in the `feature-webserver` branch before executing the `start-server` command.)
```
fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm % ls -la ./templates
total 1304
drwxr-xr-x@ 10 fukusuke  staff     320 10 14 15:51 .
drwx------@ 10 fukusuke  staff     320 10 14 15:49 ..
-rw-r--r--@  1 fukusuke  staff   44659 10 14 15:51 alpinejs.3.14.1.js
-rw-r--r--   1 fukusuke  staff    9391 10 14 15:51 common.js
-rw-r--r--@  1 fukusuke  staff   14552 10 14 15:51 computer_summary.template
-rw-r--r--@  1 fukusuke  staff   18011 10 14 15:51 content.template
-rw-r--r--@  1 fukusuke  staff   83961 10 14 15:51 font-awesome.6.0.css
-rw-r--r--@  1 fukusuke  staff   14943 10 14 15:51 index.template
-rw-r--r--@  1 fukusuke  staff  470394 10 14 15:51 tailwind.3.4.js
drwxr-xr-x@  4 fukusuke  staff     128  9 23 13:14 webfonts
fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm % ./takajo start-server -s ./html-report.sqlite -p 8089
syncio.nim(767)          open
Error: unhandled exception: cannot open: ./src/takajopkg/web/static/js/common.js [IOError]
fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm %
```

**Comment by fukusuket** [comment]
I would also appreciate it if you could confirm the following two points🙏

1. The `. /takajo help` command, the `start-server` command is not shown, so it would be better to show it!
2. It would be good if we can delete unnecessary imports.(If the warning is wrong, no action is needed!)
```
fukusuke@fukusukenoMacBook-Air takajo % nimble build -d:release --threads:on
...
cated]
/Users/fukusuke/Scripts/Nim/takajo/src/takajopkg/web/controllers/controller.nim(1, 8) Warning: imported and not used: 'json' [UnusedImport]
/Users/fukusuke/Scripts/Nim/takajo/src/takajopkg/web/controllers/controller.nim(3, 8) Warning: imported and not used: 'computers' [UnusedImport]
/Users/fukusuke/Scripts/Nim/takajo/src/takajopkg/web/controllers/rules.nim(5, 8) Warning: imported and not used: 'times' [UnusedImport]
/Users/fukusuke/Scripts/Nim/takajo/src/takajopkg/web/startServer.nim(2, 28) Warning: imported and not used: 'staticfile' [UnusedImport]

```

**Comment by YamatoSecurity** [comment]
@nishikawaakira Sorry, can you rename `start-server` command to `html-server` ? It will go nicely with `html-report` since they are similar.

**Comment by YamatoSecurity** [comment]
@nishikawaakira 横からすみません。 I changed the name from `start-server` to `html-server` and removed some of the unused imports. I also added the examples and updated some wording. Please check my commits.

Questions:
1. There is still one more unused import: `takajo/src/takajopkg/web/controllers/controller.nim(2, 8) Warning: imported and not used: 'computers' [UnusedImport]` There seems to be a `computers.nim` file with code in it, but is it not being used?
2. The usage for this command is `html-server -s ./takajo/sqlite.db -p 8089` but how do we first create the `sqlite.db` file? I think we should make the usage similar to `html-report` by using the `timeline.jsonl` as INPUT and have the command create the sqlite DB, what do you think? The other option is to create a new command `html-create-db` that creates the SQLITE database and then we can use that database as input to both `html-report` and `html-server`. Please tell me what you think the best option is. If we do the latter with the `html-create-db` command, then we only need to create the database once and then we can run both `html-report` and `html-server` later so it may increase performance.

P.S. @fukusuket I went ahead and changed the LICENSE to AGPL so we don't need to create another PR for it.

**Comment by nishikawaakira** [comment]
@YamatoSecurity @fukusuket 
Sorry for the late response.
> There is still one more unused import

It was unnecessary code, so I removed it.

> The usage for this command is html-server -s ./takajo/sqlite.db -p 8089 but how do we first create the sqlite.db file? 

The html-server command also creates a sqlite file, since we need a separate table from the html-report, I think it is better to create it with each command

**Review by fukusuket — APPROVED** [review]
Thank you so much for implementation! LGTM!!🚀

**Review by YamatoSecurity — APPROVED** [review]
@nishikawaakira LGTM! Thanks so much!

**Pull request merged**
