### PR TITLE
add triage-data cmd

### PR DESCRIPTION
**Pull request by YamatoSecurity**
create branch for traige-data command

### CODE REVIEW

**Review by fukusuket — COMMENTED** [review]
@nishikawaakira 
What I wrote on slack, I will also write here!
- I wonder if the function to link Rule Path in Detection Rule List to yml rules (Sigma rule path specification is a command line option of takajo) will be implemented in the future?
- Critical is not counted!
- The order of "info" and "low" of "Total detections" in Summary is reversed.
- The 35MB timeline.jsonl took about 5 minutes to complete! I thought it would be nice to have a progress bar like other commands

**Comment by fukusuket** [comment]
I tried to see if there was any way to speed up the processing, so I set `COMMIT` to every 10,000 transactions for the first time in `BEGIN`, and now it takes about 5 minutes -> 5 seconds! (It looks like the same data is available at a glance, but I'm sorry if I'm wrong!)
```nim
db.exec(sql"BEGIN")
var recordCount = 0
while not fileStream.atEnd:
    let line = fileStream.readLine()
    .....
            doAssert(bres)
            finalize(stmt)
            recordCount += 1
            if recordCount %% 10000 == 0:
                db.exec(sql"COMMIT")
                db.exec(sql"BEGIN")
        except CatchableError:
            echo "Invalid JSON line: ", line
db.exec(sql"COMMIT")
fileStream.close()
echo "Database file created"
```

**Comment by YamatoSecurity** [comment]
@nishikawaakira 
Right now the output is like this:
```
Database file opened
Started the triage-data command



Counting total lines. Please wait.
File: ../hayabusa/508-2020.jsonl (205.77 MB)
Total lines: 205,480

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 205480/205480 [23.5s< 0.0s,  13.11k/sec]
Database file created
Create HTML...
Create HTML completed!!
look at the "./output/index.html"
```

Can you add a logo and change the spacing and wording as following:
```
┏━━━━┳━━━┳┓┏━┳━━━┓ ┏┳━━━┓
┃┏┓┏┓┃┏━┓┃┃┃┏┫┏━┓┃ ┃┃┏━┓┃
┗┛┃┃┗┫┃ ┃┃┗┛┛┃┃ ┃┃ ┃┃┃ ┃┃
  ┃┃ ┃┗━┛┃┏┓┓┃┗━┛┣┓┃┃┃ ┃┃
  ┃┃ ┃┏━┓┃┃┃┗┫┏━┓┃┗┛┃┗━┛┃
  ┗┛ ┗┛ ┗┻┛┗━┻┛ ┗┻━━┻━━━┛
  by Yamato Security

Database file opened
Started the triage-data command

Counting total lines. Please wait.

File: ../hayabusa/508-2020.jsonl (205.77 MB)
Total lines: 205,480

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 205480/205480 [23.5s< 0.0s,  13.11k/sec]

Database file created
Creating HTML report...
HTML report completed!

Please open "./output/index.html"
```

**Comment by nishikawaakira** [comment]
@fukusuket 
https://github.com/Yamato-Security/takajo/blob/d0cf082a3f5c8a7528c82b04e5c8765e185d8df0/src/takajopkg/general.nim#L409
If msg is empty (""), would it be okay to modify the code to skip executing lines 409 and 410? Or is it correct to assign something to msg even in the triage-data? I'm not sure what should be assigned to msg, so I would appreciate your guidance.

**Comment by fukusuket** [comment]
@nishikawaakira 
I think it might be better to put a simple message like the following!(For the purpose of being as consistent as possible with other commands):
- https://github.com/Yamato-Security/takajo/blob/d0cf082a3f5c8a7528c82b04e5c8765e185d8df0/src/takajopkg/timelinePartitionDiagnostic.nim#L1
- https://github.com/Yamato-Security/takajo/blob/d0cf082a3f5c8a7528c82b04e5c8765e185d8df0/src/takajopkg/stackCmdlines.nim#L1
- https://github.com/Yamato-Security/takajo/blob/d0cf082a3f5c8a7528c82b04e5c8765e185d8df0/src/takajopkg/stackComputers.nim#L1
- https://github.com/Yamato-Security/takajo/blob/d0cf082a3f5c8a7528c82b04e5c8765e185d8df0/src/takajopkg/ttpVisualize.nim#L1

However, if the triage-data command already outputs a similar message, I think it is OK to skip it if msg is empty!

**Comment by nishikawaakira** [comment]
@fukusuket 
Thanks for your response!

@YamatoSecurity
Should we display a message, similar to the other commands?

We might want to consider removing the following two lines.
```
Database file opened
Started the triage-data command
```

**Comment by nishikawaakira** [comment]
@YamatoSecurity 
Sorry, 'Started the triage-data command' was output by an existing library, so I will leave it as is. Is it okay to set the message to 'This command will output an HTML report and create an SQLite file.'?

**Comment by YamatoSecurity** [comment]
> Sorry, 'Started the triage-data command' was output by an existing library, so I will leave it as is. Is it okay to set the message to 'This command will output an HTML report and create an SQLite file.'?

Ok, yes, leave the `Started the triage-data...`
What about setting the message to `This command will create an SQLite file and use that data to create the HTML report.` ?

**Comment by nishikawaakira** [comment]
@YamatoSecurity 
In the current library implementation, if a message is not passed to the function as described below, a blank line will appear, as shown in the attachment. Therefore, I thought it might be better to include a message, similar to the other commands. However, if the blank line is not an issue, the message can be omitted.
https://github.com/Yamato-Security/takajo/pull/166#issuecomment-2289835028

スクリーンショット_2024-08-15_19_32_11

**Comment by nishikawaakira** [comment]
I've made some corrections, so please review them when you have time. :)

**Pull request merged**
