### PR TITLE
feat: add `stack-tasks` command

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed: #97 

### Environment
- OS: macOS Sonoma version 14.2.1
- Hayabusa v2.13.0
- Nim: 2.0.2
- nimble: 0.14.2

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### help
```
% ./takajo
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Version: 2.4.0 Dev Build
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  ...
  stack-cmdlines                 stack executed command lines
  stack-logons                   stack logons by target user, target computer, source IP address and source computer
  stack-processes                stack executed processes
  stack-tasks                    stack new scheduled tasks
  ...
Command help: takajo help <COMMAND>

Examples:
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  ...
  stack-cmdlines -t ../hayabusa/timeline.jsonl -o cmdlines.csv
  stack-logons -t ../hayabusa/timeline.jsonl -o logons.csv
  stack-processes -t ../hayabusa/timeline.jsonl -o processes.csv
  stack-tasks -t ../hayabusa/timeline.jsonl -o tasks.csv
  ...
```

```
% ./takajo stack-tasks -h
Usage:
  stack-tasks [REQUIRED,optional-params]
stack new scheduled tasks
Options:
  -h, --help                            print this cligen-erated help
  --help-syntax                         advanced: prepend,plurals,..
  --version           bool    false     print version
  -i, --ignoreSysmon  bool    false     set ignoreSysmon
  --ignoreSecurity    bool    false     set ignoreSecurity
  -o=, --output=      string  ""        save results to a CSV file
  -q, --quiet         bool    false     do not display the launch banner
  -t=, --timeline=    string  REQUIRED  Hayabusa JSONL timeline (profile: any besides all-field-info*)
```

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx
```
% ./takajo stack-tasks -t timeline.jsonl -q
Started the Stack Tasks command

This command will stack new scheduled tasks.

Counting total lines. Please wait.

Total lines: 32371

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 32371/32371 [ 0.6s< 0.0s,  62.23k/sec]

2 | Administrator -> \CYAlyNSS -> cmd.exe /C tasklist > %windir%\Temp\CYAlyNSS.tmp 2>&1
2 | admmig -> \bouWFQYO -> cmd.exe /C whoami > %windir%\Temp\bouWFQYO.tmp 2>&1
1 | LOCAL SERVICE -> \FullPowersTask -> C:\Users\Public\Tools\TokenManip\FullPowers.exe -t 4932
1 | admmig -> \smbservice -> C:\WINDOWS\Temp\MpCmdRun.bat
1 | admmig -> \Microsoft\SynchronizeTimeZone -> adf
1 | admmig -> \eviltask -> C:\tools\shell.cmd

Elapsed time: 0 hours, 0 minutes, 0 seconds
```

**Review by hitenkoku — APPROVED** [review]
LGTM

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much!

**Pull request merged**
