### PR TITLE
feat: add `timeline-tasks` command

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed: #110

### Environment
- OS: macOS Sonoma version 14.2.1
- Hayabusa v2.13.0
- Nim: 2.0.2
- nimble: 0.14.2

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### help
```
% ./takajo
...
Commands:
  help                           print comprehensive or per-cmd help
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  ...
  timeline-logon                 create a CSV timeline of logon events
  timeline-partition-diagnostic  create a CSV timeline of partition diagnostic events
  timeline-suspicious-processes  create a CSV timeline of suspicious processes
  timeline-tasks                 create a CSV timeline of scheduled tasks
  ...

Command help: takajo help <COMMAND>

Examples:
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  ...
  timeline-logon -t ../hayabusa/timeline.jsonl -o logon-timeline.csv
  timeline-partition-diagnostic -t ../hayabusa/timeline.jsonl -o partition-diagnostic-timeline.csv
  timeline-suspicious-processes -t ../hayabusa/timeline.jsonl [--level medium] [-o suspicious-processes.csv]
  timeline-tasks -t ../hayabusa/timeline.jsonl -o task-timeline.csv
  ...

```
./takajo timeline-tasks -h
Usage:
  timeline-tasks [REQUIRED,optional-params]
create a CSV timeline of scheduled tasks
Options:
  -h, --help                              print this cligen-erated help
  --help-syntax                           advanced: prepend,plurals,..
  --version             bool    false     print version
  -o=, --output=        string  REQUIRED  save results to a CSV file
  --outputLogoffEvents  bool    false     set outputLogoffEvents
  -q, --quiet           bool    false     do not display the launch banner
  -t=, --timeline=      string  REQUIRED  Hayabusa JSONL timeline (profile: any)
```

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx
```
% ./takajo timeline-tasks -t timeline.jsonl -o task-timeline.csv -q
Started the Timeline Logon command

This command creates a CSV timeline of scheduled tasks.

Counting total lines. Please wait.

Total lines: 32371

Creating a logon timeline. Please wait.

100%|█████████████████████████| 32371/32371 [ 0.6s< 0.0s,  63.12k/sec]

Saved results to task-timeline.csv (12.00 KB)

Elapsed time: 0 hours, 0 minutes, 0 seconds
```

```csv
Timestamp,SubjectUserName,TaskName,Command,Arguments,SubjectUserSid,SubjectDomainName,SubjectLogonId,TaskContent,
2019-03-19 09:02:04.319 +09:00,Administrator,\CYAlyNSS,cmd.exe,/C tasklist > %windir%\Temp\CYAlyNSS.tmp 2>&1,S-1-5-21-1587066498-1489273250-1035260531-500,EXAMPLE,0x17e2d2,"<?xml version=""1.0"" encoding=""UTF-16""?><Task version=""1.2"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <Triggers> <CalendarTrigger> <StartBoundary>2015-07-15T20:35:13.2757294</StartBoundary> <Enabled>true</Enabled> <ScheduleByDay> <DaysInterval>1</DaysInterval> </ScheduleByDay> </CalendarTrigger> </Triggers> <Principals> <Principal id=""LocalSystem""> <UserId>S-1-5-18</UserId> <RunLevel>HighestAvailable</RunLevel> <LogonType>InteractiveToken</LogonType> </Principal> </Principals> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>true</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>P3D</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""LocalSystem""> <Exec> <Command>cmd.exe</Command> <Arguments>/C tasklist &gt; %windir%\Temp\CYAlyNSS.tmp 2&gt;&amp;1</Arguments> </Exec> </Actions></Task>",
2019-03-19 09:02:04.319 +09:00,Administrator,\CYAlyNSS,cmd.exe,/C tasklist > %windir%\Temp\CYAlyNSS.tmp 2>&1,S-1-5-21-1587066498-1489273250-1035260531-500,EXAMPLE,0x17e2d2,"<?xml version=""1.0"" encoding=""UTF-16""?><Task version=""1.2"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <Triggers> <CalendarTrigger> <StartBoundary>2015-07-15T20:35:13.2757294</StartBoundary> <Enabled>true</Enabled> <ScheduleByDay> <DaysInterval>1</DaysInterval> </ScheduleByDay> </CalendarTrigger> </Triggers> <Principals> <Principal id=""LocalSystem""> <UserId>S-1-5-18</UserId> <RunLevel>HighestAvailable</RunLevel> <LogonType>InteractiveToken</LogonType> </Principal> </Principals> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>true</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>P3D</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""LocalSystem""> <Exec> <Command>cmd.exe</Command> <Arguments>/C tasklist &gt; %windir%\Temp\CYAlyNSS.tmp 2&gt;&amp;1</Arguments> </Exec> </Actions></Task>",
2020-03-07 22:17:38.534 +09:00,LOCAL SERVICE,\FullPowersTask,C:\Users\Public\Tools\TokenManip\FullPowers.exe,-t 4932,S-1-5-19,NT AUTHORITY,0x3e5,"<?xml version=""1.0"" encoding=""UTF-16""?><Task version=""1.3"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <RegistrationInfo> <URI>\FullPowersTask</URI> </RegistrationInfo> <Triggers /> <Principals> <Principal id=""Author""> <UserId>S-1-5-19</UserId> <RunLevel>LeastPrivilege</RunLevel> <RequiredPrivileges> <Privilege>SeAssignPrimaryTokenPrivilege</Privilege> <Privilege>SeAuditPrivilege</Privilege> <Privilege>SeChangeNotifyPrivilege</Privilege> <Privilege>SeCreateGlobalPrivilege</Privilege> <Privilege>SeImpersonatePrivilege</Privilege> <Privilege>SeIncreaseQuotaPrivilege</Privilege> <Privilege>SeIncreaseWorkingSetPrivilege</Privilege> </RequiredPrivileges> </Principal> </Principals> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <StartWhenAvailable>false</StartWhenAvailable> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <Duration>PT10M</Duration> <WaitTimeout>PT1H</WaitTimeout> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>false</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession> <UseUnifiedSchedulingEngine>false</UseUnifiedSchedulingEngine> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>PT72H</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""Author""> <Exec> <Command>C:\Users\Public\Tools\TokenManip\FullPowers.exe</Command> <Arguments>-t 4932</Arguments> </Exec> </Actions></Task>",
2020-07-12 06:38:17.351 +09:00,admmig,\smbservice,C:\WINDOWS\Temp\MpCmdRun.bat,,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x3246775,"<?xml version=""1.0"" encoding=""UTF-16""?><Task version=""1.2"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <RegistrationInfo> <Date>2020-07-11T21:38:17</Date> <Author>OFFSEC\lambda-user</Author> </RegistrationInfo> <Triggers> <TimeTrigger> <StartBoundary>2020-07-11T15:20:00</StartBoundary> <Enabled>true</Enabled> </TimeTrigger> </Triggers> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <StartWhenAvailable>false</StartWhenAvailable> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <Duration>PT10M</Duration> <WaitTimeout>PT1H</WaitTimeout> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>false</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>PT72H</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""Author""> <Exec> <Command>C:\WINDOWS\Temp\MpCmdRun.bat</Command> </Exec> </Actions> <Principals> <Principal id=""Author""> <UserId>S-1-5-18</UserId> <RunLevel>LeastPrivilege</RunLevel> </Principal> </Principals></Task>",
2021-04-21 22:30:00.589 +09:00,admmig,\eviltask,C:\tools\shell.cmd,,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x6fc89e,"<?xml version=""1.0"" encoding=""UTF-16""?><Task version=""1.2"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <RegistrationInfo> <Date>2021-04-21T13:30:00</Date> <Author>OFFSEC\admmig</Author> <URI>\eviltask</URI> </RegistrationInfo> <Triggers> <TimeTrigger> <Repetition> <Interval>PT1M</Interval> <StopAtDurationEnd>false</StopAtDurationEnd> </Repetition> <StartBoundary>2021-04-21T13:30:00</StartBoundary> <Enabled>true</Enabled> </TimeTrigger> </Triggers> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <StartWhenAvailable>false</StartWhenAvailable> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <Duration>PT10M</Duration> <WaitTimeout>PT1H</WaitTimeout> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>false</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>PT72H</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""Author""> <Exec> <Command>C:\tools\shell.cmd</Command> </Exec> </Actions> <Principals> <Principal id=""Author""> <UserId>S-1-5-18</UserId> <RunLevel>LeastPrivilege</RunLevel> </Principal> </Principals></Task>",
2021-06-01 23:09:38.437 +09:00,admmig,\Microsoft\SynchronizeTimeZone,adf,,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x46b7b4,"<?xml version=""1.0"" encoding=""UTF-16""?><Task version=""1.2"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <RegistrationInfo> <Date>2021-06-01T16:09:38.3707854</Date> <Author>OFFSEC\admmig</Author> <URI>\Microsoft\SynchronizeTimeZone</URI> </RegistrationInfo> <Triggers> <CalendarTrigger> <StartBoundary>2021-06-01T16:09:35.8747701</StartBoundary> <Enabled>true</Enabled> <ScheduleByDay> <DaysInterval>1</DaysInterval> </ScheduleByDay> </CalendarTrigger> </Triggers> <Principals> <Principal id=""Author""> <RunLevel>LeastPrivilege</RunLevel> <UserId>OFFSEC\admmig</UserId> <LogonType>InteractiveToken</LogonType> </Principal> </Principals> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <StartWhenAvailable>false</StartWhenAvailable> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <Duration>PT10M</Duration> <WaitTimeout>PT1H</WaitTimeout> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>false</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>P3D</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""Author""> <Exec> <Command>adf</Command> </Exec> </Actions></Task>",
2021-06-11 06:21:26.383 +09:00,admmig,\bouWFQYO,cmd.exe,/C whoami > %windir%\Temp\bouWFQYO.tmp 2>&1,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x5a419bc,"<?xml version=""1.0"" encoding=""UTF-16""?><Task version=""1.2"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <Triggers> <CalendarTrigger> <StartBoundary>2015-07-15T20:35:13.2757294</StartBoundary> <Enabled>true</Enabled> <ScheduleByDay> <DaysInterval>1</DaysInterval> </ScheduleByDay> </CalendarTrigger> </Triggers> <Principals> <Principal id=""LocalSystem""> <UserId>S-1-5-18</UserId> <RunLevel>HighestAvailable</RunLevel> <LogonType>InteractiveToken</LogonType> </Principal> </Principals> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>true</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>P3D</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""LocalSystem""> <Exec> <Command>cmd.exe</Command> <Arguments>/C whoami &gt; %windir%\Temp\bouWFQYO.tmp 2&gt;&amp;1</Arguments> </Exec> </Actions> <RegistrationInfo> <URI>\bouWFQYO</URI> </RegistrationInfo></Task>",
2021-06-11 06:21:26.383 +09:00,admmig,\bouWFQYO,cmd.exe,/C whoami > %windir%\Temp\bouWFQYO.tmp 2>&1,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x5a419bc,"<?xml version=""1.0"" encoding=""UTF-16""?><Task version=""1.2"" xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task""> <Triggers> <CalendarTrigger> <StartBoundary>2015-07-15T20:35:13.2757294</StartBoundary> <Enabled>true</Enabled> <ScheduleByDay> <DaysInterval>1</DaysInterval> </ScheduleByDay> </CalendarTrigger> </Triggers> <Principals> <Principal id=""LocalSystem""> <UserId>S-1-5-18</UserId> <RunLevel>HighestAvailable</RunLevel> <LogonType>InteractiveToken</LogonType> </Principal> </Principals> <Settings> <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy> <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries> <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries> <AllowHardTerminate>true</AllowHardTerminate> <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable> <IdleSettings> <StopOnIdleEnd>true</StopOnIdleEnd> <RestartOnIdle>false</RestartOnIdle> </IdleSettings> <AllowStartOnDemand>true</AllowStartOnDemand> <Enabled>true</Enabled> <Hidden>true</Hidden> <RunOnlyIfIdle>false</RunOnlyIfIdle> <WakeToRun>false</WakeToRun> <ExecutionTimeLimit>P3D</ExecutionTimeLimit> <Priority>7</Priority> </Settings> <Actions Context=""LocalSystem""> <Exec> <Command>cmd.exe</Command> <Arguments>/C whoami &gt; %windir%\Temp\bouWFQYO.tmp 2&gt;&amp;1</Arguments> </Exec> </Actions> <RegistrationInfo> <URI>\bouWFQYO</URI> </RegistrationInfo></Task>",
```

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much for the quick PR!
I also want to parse the XML into the different fields. (Get rid of the hard to read XML...)
For example:
```
<?xml version=""1.0"" encoding=""UTF-16""?>
<Task version=""1.2""
	xmlns=""http://schemas.microsoft.com/windows/2004/02/mit/task"">
	<Triggers>
		<CalendarTrigger>
			<StartBoundary>2015-07-15T20:35:13.2757294</StartBoundary>
			<Enabled>true</Enabled>
			<ScheduleByDay>
				<DaysInterval>1</DaysInterval>
			</ScheduleByDay>
		</CalendarTrigger>
	</Triggers>
	<Principals>
		<Principal id=""LocalSystem"">
			<UserId>S-1-5-18</UserId>
			<RunLevel>HighestAvailable</RunLevel>
			<LogonType>InteractiveToken</LogonType>
		</Principal>
	</Principals>
	<Settings>
		<MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
		<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
		<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
		<AllowHardTerminate>true</AllowHardTerminate>
		<RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
		<IdleSettings>
			<StopOnIdleEnd>true</StopOnIdleEnd>
			<RestartOnIdle>false</RestartOnIdle>
		</IdleSettings>
		<AllowStartOnDemand>true</AllowStartOnDemand>
		<Enabled>true</Enabled>
		<Hidden>true</Hidden>
		<RunOnlyIfIdle>false</RunOnlyIfIdle>
		<WakeToRun>false</WakeToRun>
		<ExecutionTimeLimit>P3D</ExecutionTimeLimit>
		<Priority>7</Priority>
	</Settings>
	<Actions Context=""LocalSystem"">
		<Exec>
			<Command>cmd.exe</Command>
			<Arguments>/C tasklist &gt; %windir%\Temp\CYAlyNSS.tmp 2&gt;&amp;1</Arguments>
		</Exec>
	</Actions>
</Task>
```

will extract out `StartBoundary`, `Enabled`, `DaysInterval`, `Principal id`, etc... fields into column rows but exclude `Command`, `Arguments`, etc.. that was already extracted. (Avoid duplicates)

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking :) I also output other XML elements to CSV. What do you think?

### hayabusa-sample-evtx
```
% ./takajo timeline-tasks -t timeline.jsonl -o tasks-timeline.csv -q
Started the Timeline Tasks command

This command creates a CSV timeline of scheduled task events.

Counting total lines. Please wait.

Total lines: 32371

Creating a scheduled tasks timeline. Please wait.

100%|█████████████████████████| 32371/32371 [ 0.6s< 0.0s,  63.61k/sec]

Saved results to tasks-timeline.csv (3.76 KB)

Elapsed time: 0 hours, 0 minutes, 0 seconds
```

```csv
Timestamp,TaskName,User,SubjectUserSid,SubjectDomainName,SubjectLogonId,Command,Arguments,Triggers:CalendarTrigger:StartBoundary,Triggers:CalendarTrigger:Enabled,Triggers:CalendarTrigger:ScheduleByDay:DaysInterval,Principal:UserId,Principal:RunLevel,Principal:LogonType,Settings:MultipleInstancesPolicy,Settings:DisallowStartIfOnBatteries,Settings:StopIfGoingOnBatteries,Settings:AllowHardTerminate,Settings:RunOnlyIfNetworkAvailable,Settings:IdleSettings:StopOnIdleEnd,Settings:IdleSettings:RestartOnIdle,Settings:AllowStartOnDemand,Settings:Enabled,Settings:Hidden,Settings:RunOnlyIfIdle,Settings:WakeToRun,Settings:ExecutionTimeLimit,Settings:Priority,Principal:RequiredPrivileges:Privilege,Settings:StartWhenAvailable,Settings:IdleSettings:Duration,Settings:IdleSettings:WaitTimeout,Settings:DisallowStartOnRemoteAppSession,Settings:UseUnifiedSchedulingEngine,RegistrationInfo:URI,Triggers:TimeTrigger:StartBoundary,Triggers:TimeTrigger:Enabled,RegistrationInfo:Date,RegistrationInfo:Author,Triggers:TimeTrigger:Repetition:Interval,Triggers:TimeTrigger:Repetition:StopAtDurationEnd,
2019-03-19 09:02:04.319 +09:00,\CYAlyNSS,Administrator,S-1-5-21-1587066498-1489273250-1035260531-500,EXAMPLE,0x17e2d2,cmd.exe,/C tasklist > %windir%\Temp\CYAlyNSS.tmp 2>&1,2015-07-15T20:35:13.2757294,true,1,S-1-5-18,HighestAvailable,InteractiveToken,IgnoreNew,false,false,true,false,true,false,true,true,true,false,false,P3D,7,,,,,,,,,,,,,,
2019-03-19 09:02:04.319 +09:00,\CYAlyNSS,Administrator,S-1-5-21-1587066498-1489273250-1035260531-500,EXAMPLE,0x17e2d2,cmd.exe,/C tasklist > %windir%\Temp\CYAlyNSS.tmp 2>&1,2015-07-15T20:35:13.2757294,true,1,S-1-5-18,HighestAvailable,InteractiveToken,IgnoreNew,false,false,true,false,true,false,true,true,true,false,false,P3D,7,,,,,,,,,,,,,,
2020-03-07 22:17:38.534 +09:00,\FullPowersTask,LOCAL SERVICE,S-1-5-19,NT AUTHORITY,0x3e5,C:\Users\Public\Tools\TokenManip\FullPowers.exe,-t 4932,,,,S-1-5-19,LeastPrivilege,,IgnoreNew,true,true,true,false,true,false,true,true,false,false,false,PT72H,7,SeIncreaseWorkingSetPrivilege,false,PT10M,PT1H,false,false,\FullPowersTask,,,,,,,
2020-07-12 06:38:17.351 +09:00,\smbservice,admmig,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x3246775,C:\WINDOWS\Temp\MpCmdRun.bat,,,,,S-1-5-18,LeastPrivilege,,IgnoreNew,true,true,true,false,true,false,true,true,false,false,false,PT72H,7,,false,PT10M,PT1H,,,,2020-07-11T15:20:00,true,2020-07-11T21:38:17,OFFSEC\lambda-user,,,
2021-04-21 22:30:00.589 +09:00,\eviltask,admmig,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x6fc89e,C:\tools\shell.cmd,,,,,S-1-5-18,LeastPrivilege,,IgnoreNew,true,true,true,false,true,false,true,true,false,false,false,PT72H,7,,false,PT10M,PT1H,,,\eviltask,2021-04-21T13:30:00,true,2021-04-21T13:30:00,OFFSEC\admmig,PT1M,false,
2021-06-01 23:09:38.437 +09:00,\Microsoft\SynchronizeTimeZone,admmig,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x46b7b4,adf,,2021-06-01T16:09:35.8747701,true,1,OFFSEC\admmig,LeastPrivilege,InteractiveToken,IgnoreNew,true,true,true,false,true,false,true,true,false,false,false,P3D,7,,false,PT10M,PT1H,,,\Microsoft\SynchronizeTimeZone,,,2021-06-01T16:09:38.3707854,OFFSEC\admmig,,,
2021-06-11 06:21:26.383 +09:00,\bouWFQYO,admmig,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x5a419bc,cmd.exe,/C whoami > %windir%\Temp\bouWFQYO.tmp 2>&1,2015-07-15T20:35:13.2757294,true,1,S-1-5-18,HighestAvailable,InteractiveToken,IgnoreNew,false,false,true,false,true,false,true,true,true,false,false,P3D,7,,,,,,,\bouWFQYO,,,,,,,
2021-06-11 06:21:26.383 +09:00,\bouWFQYO,admmig,S-1-5-21-4230534742-2542757381-3142984815-1111,OFFSEC,0x5a419bc,cmd.exe,/C whoami > %windir%\Temp\bouWFQYO.tmp 2>&1,2015-07-15T20:35:13.2757294,true,1,S-1-5-18,HighestAvailable,InteractiveToken,IgnoreNew,false,false,true,false,true,false,true,true,true,false,false,P3D,7,,,,,,,\bouWFQYO,,,,,,,
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much!

**Pull request merged**
