### PR TITLE
feat: add `ttp-visualize-sigma` command

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- feat: #92 

### Environment
- OS: macOS Sonoma version 14.2.1
- Hayabusa v2.12.0
- Nim: 2.0.2
- nimble: 0.14.2

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### Help
```
fukusuke@fukusukenoMacBook-Air hayabusa-2.12.0-all-platforms % ./takajo ttp-visualize-sigma -h
Usage:
  ttp-visualize-sigma [REQUIRED,optional-params]
extract TTPs from Sigma and create a JSON file to visualize in MITRE ATT&CK Navigator
Options:
  -h, --help                                               print this cligen-erated help
  --help-syntax                                            advanced: prepend,plurals,..
  --version         bool    false                          print version
  -o=, --output=    string  "mitre-attack-navigator.json"  save results to a json file
  -q, --quiet       bool    false                          do not display the launch banner
  -r=, --rulesDir=  string  REQUIRED                       Sigma rules directory
```

```
% ./takajo
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Version: 2.3.1 Year Of The Dragon Release
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  ...
  ttp-visualize                  extract TTPs and create a JSON file to visualize in MITRE ATT&CK Navigator
  ttp-visualize-sigma            extract TTPs from Sigma and create a JSON file to visualize in MITRE ATT&CK Navigator
  ...

Command help: takajo help <COMMAND>

Examples:
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  ...
  ttp-visualize -t ../hayabusa/timeline.jsonl -o mitre-attack-navigator.json
  ttp-visualize-sigma -r ../hayabusa/rules -o mitre-attack-navigator.json
  ...
```

**Comment by fukusuket** [comment]
### hayabusa-rule
```
% ./takajo ttp-visualize-sigma -r rules -q
Started the TTP Visualize Sigma command.
This command extracts TTPs from Sigma rule and creates a JSON file to visualize in MITRE ATT&CK Navigator.

Counting total rule files. Please wait.
Total rule files: 4330

100%|█████████████████████████| 4330/4330 [ 0.1s< 0.0s,  19.16k/sec]

Saved file: mitre-attack-navigator.json (72.38 KB)

Elapsed time: 0 hours, 0 minutes, 0 seconds
```

**Comment by fukusuket** [comment]
### Sigma rule
```
% ./takajo ttp-visualize-sigma -r ~/Scripts/Python/sigma -q
Started the TTP Visualize Sigma command.
This command extracts TTPs from Sigma rule and creates a JSON file to visualize in MITRE ATT&CK Navigator.

Counting total rule files. Please wait.
Total rule files: 3454

100%|█████████████████████████| 3454/3454 [ 0.1s< 0.0s,   5.12k/sec]

Saved file: mitre-attack-navigator.json (105.53 KB)

Elapsed time: 0 hours, 0 minutes, 0 seconds
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thank you!

**Pull request merged**
