### PR TITLE
feat: add timeline-partition-diagnostic command

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- feat: #67
  -  extract `EventID` == `1006` and `Channel` == `MS-Win-Partition/Diagnostic`
  - output following field
    - `Timestamp`
    - `Computer`
    - `Manufacturer` 
    - `Model`
    - `Revision` 
    - `SerialNumber`
- related: https://github.com/Yamato-Security/hayabusa-rules/pull/534

### Environment
- OS: macOS Sonoma version 14.0
- Hayabusa v2.10.1
- Nim: 2.0.0

### Test
without -o option
スクリーンショット 2023-11-19 8 30 49

with -o option
スクリーンショット 2023-11-19 8 43 31

I would appreciate it if you could review when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
I checked with evtx on Windows 11, and the Volume Serial Number could not be extracted because the `Vbr1/Vbr2/Vbr3` fields were always empty ... (also [Partition%254DiagnosticParser_Ver1_3.py](https://github.com/theAtropos4n6/Partition-4DiagnosticParser/blob/main/Partition%254DiagnosticParser_Ver1_3.py) will fail with Windows 11 evtx)

**Comment by YamatoSecurity** [comment]
> I checked with evtx on Windows 11, and the Volume Serial Number could not be extracted because the `Vbr1/Vbr2/Vbr3` fields were always empty ... (also [Partition%254DiagnosticParser_Ver1_3.py](https://github.com/theAtropos4n6/Partition-4DiagnosticParser/blob/main/Partition%254DiagnosticParser_Ver1_3.py) will fail with Windows 11 evtx)
> 
> Therefore, this PR does not implement Volume Serial Number extraction processing.

What about implementing it for Windows systems older than Win 11? I think there is still a need for forensics on older OSes so I would like to support it and just print `NULL`, `n/a`, etc... when it is blank. Do you need a sample log to test with?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so muhc for review :) Well, it would be better if it could support Windows 10. I'll try implementing it💪
I'll check the sample log below,
- https://github.com/theAtropos4n6/Partition-4DiagnosticParser/tree/main/sampleFile
- https://github.com/NextronSystems/evtx-baseline/releases/tag/v0.8

and try implementing the following logic to extract the Volume Serial Number.
- https://github.com/theAtropos4n6/Partition-4DiagnosticParser/blob/68d0269bd56f04c0c21415f8b3fe2f4df5b0c10b/Partition%254DiagnosticParser_Ver1_3.py#L20-L35

**Comment by fukusuket** [comment]
@YamatoSecurity 
I implemented VSN extraction processing :)
I would appreciate it if you could review when you have time🙏

## TEST
I compared this PR with the `Partition%4Diagnostic.evtx Log Parser` and verified that all `VSN`s are output the same.
Test data: https://github.com/theAtropos4n6/Partition-4DiagnosticParser/tree/main/sampleFile

###  Partition%4Diagnostic.evtx Log Parser result
Media S/N | Manufacturer | Model | First connected Timestamp (UTC) | Last connected Timestamp (UTC) | Every VSN recovered from the log
-- | -- | -- | -- | -- | --
VB3b95e08d-575b8650 | NULL | VBOX HARDDISK | 2020-11-29 18:22:10.278858 UTC | 2020-11-30 03:27:04.222625 UTC | 6E36F720 FC3CB3DD 5818CA15
007B01149030 |   | Patriot Memory | 2020-11-29 08:51:44.728821 UTC | 2020-11-29 17:28:56.966512 UTC | C8B91B23 76D3169C 56EE2567 54F63E46 D803E772 30239D59 6ECA9A94 CA19B8CD 8C09DE0F DAFBDA6E
EE04D1505CE9 | Kingston | DT microDuo 3C | 2020-11-29 09:22:33.826977 UTC | 2020-11-29 09:22:33.826977 UTC | GPT - NO VSN INFO
001CC0EC3458F110E5F31400 | Kingston | DataTraveler G3 | 2020-11-29 09:25:07.912113 UTC | 2020-11-29 09:53:05.742238 UTC | 6A844219 2C50410B

### This PR(with o option's csv)
```csv
Timestamp,Computer,Manufacturer,Model,Revision,SerialNumber,VSN0,VSN1,VSN2,VSN3
2020-11-29 17:36:03.263 +09:00,DESKTOP-GOGB42D,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,5818CA15,n/a
2020-11-29 17:49:04.111 +09:00,DESKTOP-GOGB42D,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,5818CA15,n/a
2020-11-29 17:51:44.728 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,C8B91B23,76D3169C,56EE2567,n/a
2020-11-29 18:04:26.748 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,C8B91B23,76D3169C,56EE2567,n/a
2020-11-29 18:04:45.710 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,C8B91B23,76D3169C,n/a,n/a
2020-11-29 18:04:59.624 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,C8B91B23,n/a,n/a,n/a
2020-11-29 18:05:11.925 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,n/a,n/a,n/a,n/a
2020-11-29 18:06:44.210 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,n/a,n/a,n/a,n/a
2020-11-29 18:06:45.637 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,54F63E46,n/a,n/a,n/a
2020-11-29 18:07:05.636 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,54F63E46,n/a,n/a,n/a
2020-11-29 18:07:12.211 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,54F63E46,D803E772,n/a,n/a
2020-11-29 18:07:57.760 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,54F63E46,D803E772,n/a,n/a
2020-11-29 18:08:01.816 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,54F63E46,D803E772,30239D59,n/a
2020-11-29 18:18:44.808 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,54F63E46,D803E772,n/a,n/a
2020-11-29 18:18:51.794 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,54F63E46,n/a,n/a,n/a
2020-11-29 18:19:00.325 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,n/a,n/a,n/a,n/a
2020-11-29 18:19:49.585 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,n/a,n/a,n/a,n/a
2020-11-29 18:19:52.675 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,6ECA9A94,n/a,n/a,n/a
2020-11-29 18:22:33.826 +09:00,DESKTOP-GOGB42D,Kingston,DT microDuo 3C,PMAP,EE04D1505CE9,n/a,n/a,n/a,n/a
2020-11-29 18:22:52.398 +09:00,DESKTOP-GOGB42D,Kingston,DT microDuo 3C,PMAP,EE04D1505CE9,n/a,n/a,n/a,n/a
2020-11-29 18:24:30.370 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,n/a,n/a,n/a,n/a
2020-11-29 18:25:07.912 +09:00,DESKTOP-GOGB42D,Kingston,DataTraveler G3,1.00,001CC0EC3458F110E5F31400,6A844219,n/a,n/a,n/a
2020-11-29 18:25:43.042 +09:00,DESKTOP-GOGB42D,Kingston,DataTraveler G3,1.00,001CC0EC3458F110E5F31400,n/a,n/a,n/a,n/a
2020-11-29 18:27:32.406 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,6ECA9A94,n/a,n/a,n/a
2020-11-29 18:29:17.031 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,n/a,n/a,n/a,n/a
2020-11-29 18:47:03.949 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,DAFBDA6E,8C09DE0F,CA19B8CD,n/a
2020-11-29 18:50:25.266 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,n/a,n/a,n/a,n/a
2020-11-29 18:52:07.885 +09:00,DESKTOP-GOGB42D,Kingston,DataTraveler G3,1.00,001CC0EC3458F110E5F31400,2C50410B,n/a,n/a,n/a
2020-11-29 18:52:41.120 +09:00,DESKTOP-GOGB42D,Kingston,DataTraveler G3,1.00,001CC0EC3458F110E5F31400,n/a,n/a,n/a,n/a
2020-11-29 18:53:05.742 +09:00,DESKTOP-GOGB42D,Kingston,DataTraveler G3,1.00,001CC0EC3458F110E5F31400,2C50410B,n/a,n/a,n/a
2020-11-29 18:53:21.846 +09:00,DESKTOP-GOGB42D,Kingston,DataTraveler G3,1.00,001CC0EC3458F110E5F31400,n/a,n/a,n/a,n/a
2020-11-30 02:28:56.966 +09:00,DESKTOP-GOGB42D,,Patriot Memory,PMAP,007B01149030,n/a,n/a,n/a,n/a
2020-11-30 03:22:10.278 +09:00,WIN-9F6UT4I01JI,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,n/a,n/a
2020-11-30 03:26:04.257 +09:00,WIN-9F6UT4I01JI,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,n/a,n/a
2020-11-30 03:26:04.271 +09:00,WIN-9F6UT4I01JI,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,n/a,n/a
2020-11-30 03:26:04.383 +09:00,WIN-9F6UT4I01JI,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,5818CA15,n/a
2020-11-30 03:26:05.085 +09:00,WIN-9F6UT4I01JI,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,5818CA15,n/a
2020-11-30 03:26:58.294 +09:00,DESKTOP-GOGB42D,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,5818CA15,n/a
2020-11-30 04:45:37.205 +09:00,DESKTOP-GOGB42D,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,5818CA15,n/a
2020-11-30 12:27:04.222 +09:00,DESKTOP-GOGB42D,NULL,VBOX HARDDISK,1.0,VB3b95e08d-575b8650,6E36F720,FC3CB3DD,5818CA15,n/a
```

**Comment by fukusuket** [comment]
Sorry, when I tried it with other Win10 event logs, I got an error... so I'll fix it!

**Comment by fukusuket** [comment]
I fixed! However, I could not check logs with VSN on my Windows 10 Home edition, so there may be some edition and recording conditions...🤔

**Review by hitenkoku — APPROVED** [review]
Thanks for your pull request.
LGTM.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you for updating changelogs :)  I added Japanese translation!

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Thanks so much! I will merge this then.

**Pull request merged**
