### PR TITLE
feat: add `stack-dns`

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed: #95 

### Environment
- OS: macOS Sonoma version 14.2.1
- Hayabusa v2.13.0
- Nim: 2.0.2
- nimble: 0.14.2

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### help
```
% ./takajo
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Version: 2.4.0 Dev Build
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  ...
  stack-dns                      stack DNS queries and responses
  stack-logons                   stack logons by target user, target computer, source IP address and source computer
  stack-processes                stack executed processes
  sysmon-process-tree            output the process tree of a certain process
  ...

Command help: takajo help <COMMAND>

Examples:
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  ...
  stack-logons -t ../hayabusa/timeline.jsonl -o logons.csv
  stack-processes -t ../hayabusa/timeline.jsonl -o processes.csv
  stack-dns -t ../hayabusa/timeline.jsonl -o dns.csv
  sysmon-process-tree -t ../hayabusa/timeline.jsonl -p <Process GUID> [-o process-tree.txt]
  ...
```

```
% ./takajo stack-dns -h
Usage:
  stack-dns [REQUIRED,optional-params]
stack DNS queries and responses
Options:
  -h, --help                          print this cligen-erated help
  --help-syntax                       advanced: prepend,plurals,..
  --version         bool    false     print version
  -o=, --output=    string  ""        save results to a CSV file
  -q, --quiet       bool    false     do not display the launch banner
  -t=, --timeline=  string  REQUIRED  Hayabusa JSONL timeline (profile: any besides all-field-info*)
```

**Comment by fukusuket** [comment]
### evtx-baseline-v8

```
% ./takajo stack-dns -t all-timeline.jsonl -o dns.csv -q
Started the Stack DNS command

This command will stack DNS queries and responses.

Counting total lines. Please wait.

Total lines: 2499299

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 2499299/2499299 [45.8s< 0.0s,  77.82k/sec]


Saved file: dns.csv (814.35 KB)

Elapsed time: 0 hours, 0 minutes, 47 seconds
```
```
% head dns.csv
Count,DNS query and response
33,C:\Windows\System32\svchost.exe -> localhost -> ::1;::ffff:127.0.0.1;
28,C:\Windows\System32\svchost.exe -> displaycatalog.mp.microsoft.com -> type: 5 displaycatalog-rp.md.mp.microsoft.com.akadns.net;type: 5 displaycatalog-rp-europe.md.mp.microsoft.com.akadns.net;type: 5 consumerrp-displaycatalog-aks2eap-europe.md.mp.microsoft.com.akadns.net;type: 5 consumerrp-displaycatalog-aks2aks-europe.md.mp.microsoft.com.akadns.net;type: 5 neu-consumerrp-displaycatalog-aks2aks-europe.md.mp.microsoft.com.akadns.net;::ffff:20.54.104.15;
24,C:\Windows\System32\svchost.exe -> wpad -> -
20,C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe -> wpad -> 192.168.0.1;192.168.0.1;fd00::3ea6:2fff:fe57:2ec6;2a02:908:187:f200:3ea6:2fff:fe57:2ec6;
19,C:\Program Files\Mozilla Firefox\pingsender.exe -> incoming.telemetry.mozilla.org -> type: 5 telemetry-incoming.r53-2.services.mozilla.com;type: 5 prod.ingestion-edge.prod.dataops.mozgcp.net;::ffff:34.120.208.123;
19,C:\Program Files (x86)\Microsoft\EdgeWebView\Application\90.0.818.66\msedgewebview2.exe -> wpad -> -
16,C:\Windows\System32\svchost.exe -> displaycatalog.mp.microsoft.com -> type: 5 displaycatalog-rp.md.mp.microsoft.com.akadns.net;type: 5 displaycatalog-rp-europe.md.mp.microsoft.com.akadns.net;type: 5 consumerrp-displaycatalog-aks2eap-europe.md.mp.microsoft.com.akadns.net;type: 5 consumerrp-displaycatalog-aks2aks-europe.md.mp.microsoft.com.akadns.net;type: 5 neu-consumerrp-displaycatalog-aks2aks-europe.md.mp.microsoft.com.akadns.net;::ffff:20.54.7.98;
14,C:\Program Files (x86)\Dropbox\Client\Dropbox.exe -> d.dropbox.com -> type: 5 d.v.dropbox.com;type: 5 d-edge.v.dropbox.com;::ffff:162.125.8.20;
14,C:\Program Files\Mozilla Firefox\firefox.exe -> prod.ingestion-edge.prod.dataops.mozgcp.net -> 34.120.208.123;
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thank you!

**Review by hitenkoku — APPROVED** [review]
LGTM

**Pull request merged**
