### PR TITLE
chg: use malebolgia to fix compile warning

### LINKED ISSUE #81: Deprecated usage of `spawn` in VT lookup commands
After updating nim to 2.0.2 with `choosenim update stable` I am getting the following error:
```
takajo-main/src/takajo.nim(15, 8) Warning: use the nimble packages `malebolgia`, `taskpools` or `weave` instead; threadpool is deprecated [Deprecated]
```

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #81 
  - Changed `threadpool` to `malebolgia` 

### Integration-Test
https://github.com/Yamato-Security/takajo/actions/runs/11415441537

### Takajo Release Automation
https://github.com/Yamato-Security/takajo/actions/workflows/release.yml

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### vt-domain-lookup
```
fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm % ./takajo vt-domain-lookup -a xxx --domainList domain.txt -o result.csv -q
Started the VirusTotal Domain Lookup command

This command will lookup a list of domains on VirusTotal.
Specify -j results.json to save the original JSON responses.
The default rate is 4 requests per minute so increase this if you have a premium membership.

Loading domains. Please wait.

Loaded domains: 5
Rate limit per minute: 4

Estimated time: 0 hours, 1 minutes, 15 seconds

100%|█████████████████████████| 5/5 [60.6s< 0.0s,  66.66m/sec]

Finished querying domains. 5 Malicious domains found.

Found malicious domains: xxx (Malicious count: 11)
Found malicious domains: xxx (Malicious count: 1)
Found malicious domains: xxx (Malicious count: 10)
Found malicious domains: xxx (Malicious count: 12)
Found malicious domains: xxx (Malicious count: 14)

Saved CSV results to result.csv (4.00 KB)

Elapsed time: 0 hours, 1 minutes, 0 seconds
```

**Comment by fukusuket** [comment]
### vt-ip-lookup(macOS)
```
./takajo vt-ip-lookup -a xxx --ipList ip.txt -o result.csv -q
Started the VirusTotal IP Lookup command

This command will lookup a list of IP addresses on VirusTotal.
Specify -j results.json to save the original JSON responses.
The default rate is 4 requests per minute so increase this if you have a premium membership.

Loading IP addresses. Please wait.

Loaded IP addresses: 5
Rate limit per minute: 4

Estimated time: 0 hours, 1 minutes, 15 seconds

100%|█████████████████████████| 5/5 [60.3s< 0.0s,  66.64m/sec]

Finished querying IP addresses. 4 Malicious IP addresses found.

Found malicious IP address: xxx (Malicious count: 8)
Found malicious IP address: xxx (Malicious count: 5)
Found malicious IP address: xxx (Malicious count: 7)
Found malicious IP address: xxx (Malicious count: 2)

Saved CSV results to result.csv (8.00 KB)

Elapsed time: 0 hours, 1 minutes, 0 seconds
```

**Comment by fukusuket** [comment]
### vt-hash-lookup(macOS)
```
./takajo vt-hash-lookup -a xxx --hashList hash.txt -o result.csv -q
Started the VirusTotal Hash Lookup command

This command will lookup a list of file hashes on VirusTotal.
Specify -j results.json to save the original JSON responses.
The default rate is 4 requests per minute so increase this if you have a premium membership.

Loading hashes. Please wait.

Loaded hashes: 4
Rate limit per minute: 4

Estimated time: 0 hours, 1 minutes, 0 seconds

100%|█████████████████████████| 4/4 [45.3s< 0.0s,  66.64m/sec]

Finished querying hashes. 1 Malicious hashes found.

Found malicious hashes: xxx (Malicious count: 52)
Hash not found: xxx
Hash not found: xxx
Hash not found: xxx

Saved CSV results to result.csv (892 Bytes)

Elapsed time: 0 hours, 0 minutes, 45 seconds
```

**Comment by fukusuket** [comment]
Only `takajo.nimble` has a conflict with #193, so I will resolve the conflict when either one is merged!💪

**Comment by fukusuket** [comment]
### Compile(macOS)
```
fukusuke@fukusukenoMacBook-Air takajo % source ~/.bash_profile 
fukusuke@fukusukenoMacBook-Air takajo % nim -v
Nim Compiler Version 2.2.0 [MacOSX: amd64]
Compiled at 2024-10-14
Copyright (c) 2006-2024 by Andreas Rumpf

active boot switches: -d:release
fukusuke@fukusukenoMacBook-Air takajo % nimble -v
nimble v0.16.1 compiled at 2024-10-14 06:26:19
git hash: couldn't determine git hash
fukusuke@fukusukenoMacBook-Air takajo % nimble build -d:releaase --threads:on
  Verifying dependencies for takajo@2.7.0
     Info:  Dependency on cligen@>= 1.7.6 already satisfied
  Verifying dependencies for cligen@1.7.6
     Info:  Dependency on suru@#f6f1e607c585b2bc2f71309996643f0555ff6349 already satisfied
  Verifying dependencies for suru@0.3.1
     Info:  Dependency on puppy@>= 2.1.0 already satisfied
  Verifying dependencies for puppy@2.1.2
     Info:  Dependency on libcurl@>= 1.0.0 already satisfied
  Verifying dependencies for libcurl@1.0.0
     Info:  Dependency on zippy@>= 0.10.0 already satisfied
  Verifying dependencies for zippy@0.10.11
     Info:  Dependency on webby@>= 0.2.0 already satisfied
  Verifying dependencies for webby@0.2.1
     Info:  Dependency on termstyle@any version already satisfied
  Verifying dependencies for termstyle@0.1.0
     Info:  Dependency on nancy@any version already satisfied
  Verifying dependencies for nancy@0.1.1
     Info:  Dependency on ansiparse@>= 0.2.0 already satisfied
  Verifying dependencies for ansiparse@0.4.0
     Info:  Dependency on malebolgia@any version already satisfied
  Verifying dependencies for malebolgia@0.1.0
     Info:  Dependency on jsony@>= 1.1.5 already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on db_connector@>= 0.1.0 already satisfied
  Verifying dependencies for db_connector@0.1.0
   Building takajo/takajo using c backend
fukusuke@fukusukenoMacBook-Air takajo % 


```

**Review by YamatoSecurity — APPROVED** [review]
LGTM! Thanks so much!

**Pull request merged**
