### PR TITLE
feat: add `stack-services`

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed: #96  

### Environment
- OS: macOS Sonoma version 14.2.1
- Hayabusa v2.13.0
- Nim: 2.0.2
- nimble: 0.14.2

### CODE REVIEW

**Comment by fukusuket** [comment]
### help

```
./takajo
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Version: 2.4.0 Dev Build
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  ...
  stack-logons                   stack logons by target user, target computer, source IP address and source computer
  stack-processes                stack executed processes
  stack-services                 stack service names and paths
  ...

Command help: takajo help <COMMAND>

Examples:
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  ...
  stack-logons -t ../hayabusa/timeline.jsonl -o logons.csv
  stack-processes -t ../hayabusa/timeline.jsonl -o processes.csv
  stack-services -t ../hayabusa/timeline.jsonl -o services.csv
  sysmon-process-tree -t ../hayabusa/timeline.jsonl -p <Process GUID> [-o process-tree.txt]
  ...
```

```
% ./takajo stack-services -h
Usage:
  stack-services [REQUIRED,optional-params]
stack service names and paths
Options:
  -h, --help                          print this cligen-erated help
  --help-syntax                       advanced: prepend,plurals,..
  --version         bool    false     print version
  -o=, --output=    string  ""        save results to a CSV file
  -q, --quiet       bool    false     do not display the launch banner
  -t=, --timeline=  string  REQUIRED  Hayabusa JSONL timeline (profile: any besides all-field-info*)
```

**Comment by fukusuket** [comment]
Sorry... I didn't have the 4697 event at hand. Could you please check if there is a 4697 event?🙏

**Comment by YamatoSecurity** [comment]
@fukusuket Sorry, Security 4697 is not enabled by default so is not common. Can you also add the more common default log System 7040? I believe the field names are the same: `Svc` and `Path`.

**Comment by YamatoSecurity** [comment]
There are Security 4697 logs in baseline-evtx/win2022-evtx/Security.evtx from https://github.com/NextronSystems/evtx-baseline/releases
I tried it but it did not have any results. 
Also, it does not output anything when `-o` is not specified. If there are no results and `-o` is not specified, we should output an error message `No results where found.`. If there are results, we should output to the screen like `stack-processes`

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks for the update. Hayabusa abbreviates the `Security` channel to `Sec` so I changed it and confirmed that it works now.

**Comment by YamatoSecurity** [comment]
Can you add options to ignore system or security logs?
                "ignoreSystem": "exclude System 7040 events",
                "ignoreSecurity": "exclude Security 4697 events",

            short = {
                "ignoreSystem": 'y',
                "ignoreSecurity": 'e'
            }

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking :) I fixed it and confirmed that it is output!

```
% ./takajo stack-services -h
Usage:
  stack-services [REQUIRED,optional-params]
stack service names and paths
Options:
  -h, --help                              print this cligen-erated help
  --help-syntax                           advanced: prepend,plurals,..
  --version             bool    false     print version
  -y, --ignoreSysmon    bool    false     set ignoreSysmon
  -e, --ignoreSecurity  bool    false     set ignoreSecurity
  -o=, --output=        string  ""        save results to a CSV file
  -q, --quiet           bool    false     do not display the launch banner
  -t=, --timeline=      string  REQUIRED  Hayabusa JSONL timeline (profile: any besides all-field-info*)
```

```
 % ./takajo stack-services -t all-timeline.jsonl -q
Started the Stack Services command

This command will stack service names and paths.

Counting total lines. Please wait.

Total lines: 2499299

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 2499299/2499299 [47.2s< 0.0s,  75.19k/sec]

1 | CDPUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k UnistackSvcGroup
1 | CaptureService_340dbd -> C:\Windows\system32\svchost.exe -k LocalService -p
1 | ConsentUxUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k DevicesFlow
1 | UserDataSvc_340dbd -> C:\Windows\system32\svchost.exe -k UnistackSvcGroup
1 | PimIndexMaintenanceSvc_340dbd -> C:\Windows\system32\svchost.exe -k UnistackSvcGroup
1 | CredentialEnrollmentManagerUserSvc_340dbd -> C:\Windows\system32\CredentialEnrollmentManager.exe
1 | UnistoreSvc_340dbd -> C:\Windows\System32\svchost.exe -k UnistackSvcGroup
1 | DevicePickerUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k DevicesFlow
1 | DevicesFlowUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k DevicesFlow
1 | cbdhsvc_340dbd -> C:\Windows\system32\svchost.exe -k ClipboardSvcGroup -p
1 | PrintWorkflowUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k PrintWorkflow
1 | DeviceAssociationBrokerSvc_340dbd -> C:\Windows\system32\svchost.exe -k DevicesFlow -p
1 | UdkUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k UdkSvcGroup
1 | WpnUserService_340dbd -> C:\Windows\system32\svchost.exe -k UnistackSvcGroup
1 | MpKsl6680716f -> C:\ProgramData\Microsoft\Windows Defender\Definition Updates\{94297FD4-6E63-4B60-B47B-85D76376014D}\MpKslDrv.sys

Saved file:  (0 Bytes)

Elapsed time: 0 hours, 0 minutes, 48 seconds
```

**Comment by YamatoSecurity** [comment]
@fukusuket Sorry one more thing. Is it possible to sort by count with the high number at top but also sort by alphabet? So if the count is all 1, I think it would be easier to read if they were sorted by alphabet rather than random.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking:) I changed to sort alphabetically!
```
% ./takajo stack-services -t all-timeline.jsonl -q
Started the Stack Services command

This command will stack service names and paths.

Counting total lines. Please wait.

Total lines: 2499299

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 2499299/2499299 [46.3s< 0.0s,  79.70k/sec]

1 | CDPUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k UnistackSvcGroup
1 | CaptureService_340dbd -> C:\Windows\system32\svchost.exe -k LocalService -p
1 | ConsentUxUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k DevicesFlow
1 | CredentialEnrollmentManagerUserSvc_340dbd -> C:\Windows\system32\CredentialEnrollmentManager.exe
1 | DeviceAssociationBrokerSvc_340dbd -> C:\Windows\system32\svchost.exe -k DevicesFlow -p
1 | DevicePickerUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k DevicesFlow
1 | DevicesFlowUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k DevicesFlow
1 | MpKsl6680716f -> C:\ProgramData\Microsoft\Windows Defender\Definition Updates\{94297FD4-6E63-4B60-B47B-85D76376014D}\MpKslDrv.sys
1 | PimIndexMaintenanceSvc_340dbd -> C:\Windows\system32\svchost.exe -k UnistackSvcGroup
1 | PrintWorkflowUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k PrintWorkflow
1 | UdkUserSvc_340dbd -> C:\Windows\system32\svchost.exe -k UdkSvcGroup
1 | UnistoreSvc_340dbd -> C:\Windows\System32\svchost.exe -k UnistackSvcGroup
1 | UserDataSvc_340dbd -> C:\Windows\system32\svchost.exe -k UnistackSvcGroup
1 | WpnUserService_340dbd -> C:\Windows\system32\svchost.exe -k UnistackSvcGroup
1 | cbdhsvc_340dbd -> C:\Windows\system32\svchost.exe -k ClipboardSvcGroup -p

Saved file:  (0 Bytes)

Elapsed time: 0 hours, 0 minutes, 47 seconds
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Thanks so much! LGTM!

**Pull request merged**
