### PR TITLE
fix: Release Automation GitHub Actions add copy templates folder

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
Related: #184 
- Added coping template folder step
- Added the ability to specify the tag name and branch name to build Takajo  

## Test
Add parameter to allow branch/tag names to be specified as follows.
- `release_ver`: Version number to use for file names
- `branch_or_tag`: Branch or tag name to build takajo
スクリーンショット 2024-09-08 20 19 20

Actions succeeded as follows
https://github.com/Yamato-Security/takajo/actions/runs/10759326195

The zip could be downloaded as follows
スクリーンショット 2024-09-08 20 17 18

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
```
fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm % pwd
/Users/fukusuke/Downloads/release-binaries-macos-latest/takajo-2.6.0-mac-arm
fukusuke@fukusukenoMacBook-Air takajo-2.6.0-mac-arm % ./takajo
┏━━━━┳━━━┳┓┏━┳━━━┓ ┏┳━━━┓
┃┏┓┏┓┃┏━┓┃┃┃┏┫┏━┓┃ ┃┃┏━┓┃
┗┛┃┃┗┫┃ ┃┃┗┛┛┃┃ ┃┃ ┃┃┃ ┃┃
  ┃┃ ┃┗━┛┃┏┓┓┃┗━┛┣┓┃┃┃ ┃┃
  ┃┃ ┃┏━┓┃┃┃┗┫┏━┓┃┗┛┃┗━┛┃
  ┗┛ ┗┛ ┗┻┛┗━┻┛ ┗┻━━┻━━━┛
  by Yamato Security

Version: 2.6.0 HITCON Release
Usage: takajo.exe <COMMAND>

Commands:
  help                           print comprehensive or per-cmd help
  automagic                      automatically executes as many commands as possible and output results to a new folder
  extract-scriptblocks           extract and reassemble PowerShell EID 4104 script block logs
  html-report                    create HTML summary reports for rules and computers with detections
  list-domains                   create a list of unique domains to be used with vt-domain-lookup
  list-hashes                    create a list of process hashes to be used with vt-hash-lookup
  list-ip-addresses              create a list of unique target and/or source IP addresses to be used with vt-ip-lookup
  list-undetected-evtx           create a list of undetected evtx files
  list-unused-rules              create a list of unused sigma rules
  split-csv-timeline             split up a large CSV file into smaller ones based on the computer name
  split-json-timeline            split up a large JSONL timeline into smaller ones based on the computer name
  stack-cmdlines                 stack executed command lines
  stack-computers                stack computers
  stack-dns                      stack DNS queries and responses
  stack-ip-addresses             stack the target IP addresses (TgtIP field) or source IP addresses (SrcIP field)
  stack-logons                   stack logons by target user, target computer, source IP address and source computer
  stack-processes                stack executed processes
  stack-services                 stack service names and paths from System 7040 and Security 4697 events
  stack-tasks                    stack new scheduled tasks from Security 4698 events and parse out XML task content
  stack-users                    stack target users (TgtUser field) or source users (SrcUser field)
  sysmon-process-tree            output the process tree of a certain process
  timeline-logon                 create a CSV timeline of logon events
  timeline-partition-diagnostic  create a CSV timeline of partition diagnostic events
  timeline-suspicious-processes  create a CSV timeline of suspicious processes
  timeline-tasks                 create a CSV timeline of scheduled tasks
  ttp-summary                    summarize tactics and techniques found in each computer
  ttp-visualize                  extract TTPs and create a JSON file to visualize in MITRE ATT&CK Navigator
  ttp-visualize-sigma            extract TTPs from Sigma and create a JSON file to visualize in MITRE ATT&CK Navigator
  vt-domain-lookup               look up a list of domains on VirusTotal
  vt-hash-lookup                 look up a list of hashes on VirusTotal
  vt-ip-lookup                   look up a list of IP addresses on VirusTotal

Command help: takajo help <COMMAND>

Examples:
  automagic -t ../hayabusa/timeline.jsonl [--level low] [--displayTable] -o case-1
  extract-scriptblocks -t ../hayabusa/timeline.jsonl [--level low] -o scriptblock-logs
  html-report -t ../hayabusa/timeline.jsonl -o ./output -r ../hayabusa/rules [--sqlite-output] [--clobber] [--skipProgressBar]
  list-domains -t ../hayabusa/timeline.jsonl [--skipProgressBar] -o domains.txt
  list-hashes -t ../hayabusa/case-1.jsonl [--skipProgressBar] -o case-1
  list-ip-addresses -t ../hayabusa/timeline.jsonl [--skipProgressBar] -o ipAddresses.txt
  list-undetected-evtx -t ../hayabusa/timeline.csv -e ../hayabusa-sample-evtx
  list-unused-rules -t ../hayabusa/timeline.csv -r ../hayabusa/rules
  split-csv-timeline -t ../hayabusa/timeline.csv [--makeMultiline] -o case-1-csv
  split-json-timeline -t ../hayabusa/timeline.jsonl -o case-1-json
  stack-cmdlines -t ../hayabusa/timeline.jsonl [--level low] [--skipProgressBar] -o cmdlines.csv
  stack-computers -t ../hayabusa/timeline.jsonl [--level informational] [--sourceComputers] [--skipProgressBar] -o computers.csv
  stack-dns -t ../hayabusa/timeline.jsonl [--level infomational] [--skipProgressBar] -o dns.csv
  stack-ip-addresses -t ../hayabusa/timeline.jsonl [--level infomational] [--targetIpAddresses] [--skipProgressBar] -o ipAddresses.csv
  stack-logons -t ../hayabusa/timeline.jsonl [--skipProgressBar] [--failedLogons] -o logons.csv
  stack-processes -t ../hayabusa/timeline.jsonl [--level low] [--skipProgressBar] -o processes.csv
  stack-services -t ../hayabusa/timeline.jsonl [--level infomational] [--skipProgressBar] -o services.csv
  stack-tasks -t ../hayabusa/timeline.jsonl [--level infomational] [--skipProgressBar] -o tasks.csv
  stack-users -t ../hayabusa/timeline.jsonl [--level infomational] [--sourceUsers] [--filterSystemAccounts] [--filterComputerAccounts] [--skipProgressBar] -o users.csv
  sysmon-process-tree -t ../hayabusa/timeline.jsonl -p <Process GUID> [-o process-tree.txt]
  timeline-logon -t ../hayabusa/timeline.jsonl [--skipProgressBar] -o logon-timeline.csv
  timeline-partition-diagnostic -t ../hayabusa/timeline.jsonl [--skipProgressBar] -o partition-diagnostic-timeline.csv
  timeline-suspicious-processes -t ../hayabusa/timeline.jsonl [--level medium] [--skipProgressBar] [-o suspicious-processes.csv]
  timeline-tasks -t ../hayabusa/timeline.jsonl [--skipProgressBar] -o task-timeline.csv
  ttp-summary -t ../hayabusa/timeline.jsonl [--skipProgressBar] -o ttp-summary.csv
  ttp-visualize -t ../hayabusa/timeline.jsonl [--skipProgressBar] -o mitre-ttp-heatmap.json
  ttp-visualize-sigma -r ../hayabusa/rules -o sigma-rules-heatmap.json
  vt-domain-lookup  -a <API-KEY> --domainList domains.txt -r 1000 -o results.csv --jsonOutput responses.json
  vt-hash-lookup -a <API-KEY> --hashList case-1-MD5-hashes.txt -r 1000 -o results.csv --jsonOutput responses.json
  vt-ip-lookup -a <API-KEY> --ipList ipAddresses.txt -r 1000 -o results.csv --jsonOutput responses.json
```

**Comment by fukusuket** [comment]
and `html-report` command succeeded as follows.
```
% ./takajo html-report -t ~/Hayabusa/hayabusa-2.17.0-mac-arm/timeline.jsonl -o out -C -q
Started the html-report command

This command will create HTML summary reports for rules and computers with detections

Counting total lines. Please wait.

File: /Users/fukusuke/Hayabusa/hayabusa-2.17.0-mac-arm/timeline.jsonl (42.02 MB)
Total lines: 32,352

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 32352/32352 [ 1.5s< 0.0s,  38.75k/sec]

Database file created.
Creating HTML report. Please wait.

HTML report completed.

Please open "./out/index.html"
```

**Review by YamatoSecurity — CHANGES_REQUESTED** [review]
@fukusuket 
Thanks so much! Looks good but the directory structure for the macos-latest zip seems different.
Could I ask the following?

1. Move the Readme and Changelog PDFs outside of the `.zip` files. I will upload them separately. Also, can you change `CHANGELOG.pdf` to `CHANGELOG-2.6.0-English.pdf` and `CHANGELOG-2.6.0-Japanese.pdf`?
It looks like the mac-arm.zip file is inside the zip? I think we need to remove this along with the changelog and readme files.

2. Change the following zip filenames:
 * `release-binaries-macos-12.zip` -> `takajo-2.6.0-mac-intel.zip`
 * `release-binaries-macos-latest.zip` -> `takajo-2.6.0-mac-arm.zip`
 * `release-binaries-ubuntu-latest.zip` -> `takajo-2.6.0-linux-intel.zip`
 * `release-binaries-windows-latest.zip` -> `takajo-2.6.0-win-intel.zip`

3. Let's keep the binary names similar to Hayabusa. `takajo.exe` -> `takajo-2.6.0-win-x64.exe`, etc... (`takajo-2.6.0-mac-x64`, `takajo-2.6.0-mac-aarch64`, `takajo-2.6.0-lin-x64-gnu`)

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking :)  I fixed https://github.com/Yamato-Security/takajo/pull/185#pullrequestreview-2288619861 !

Actions:
https://github.com/Yamato-Security/takajo/actions/runs/10773140757

Artifacts:
スクリーンショット 2024-09-09 21 35 39

html-report:
```
% ./takajo-2.6.0-mac-aarch64 html-report -t ~/Hayabusa/hayabusa-2.17.0-mac-arm/timeline.jsonl -o out
┏━━━━┳━━━┳┓┏━┳━━━┓ ┏┳━━━┓
┃┏┓┏┓┃┏━┓┃┃┃┏┫┏━┓┃ ┃┃┏━┓┃
┗┛┃┃┗┫┃ ┃┃┗┛┛┃┃ ┃┃ ┃┃┃ ┃┃
  ┃┃ ┃┗━┛┃┏┓┓┃┗━┛┣┓┃┃┃ ┃┃
  ┃┃ ┃┏━┓┃┃┃┗┫┏━┓┃┗┛┃┗━┛┃
  ┗┛ ┗┛ ┗┻┛┗━┻┛ ┗┻━━┻━━━┛
  by Yamato Security

Started the html-report command

This command will create HTML summary reports for rules and computers with detections

Counting total lines. Please wait.

File: /Users/fukusuke/Hayabusa/hayabusa-2.17.0-mac-arm/timeline.jsonl (42.02 MB)
Total lines: 32,352

Scanning the Hayabusa timeline. Please wait.

100%|█████████████████████████| 32352/32352 [ 1.5s< 0.0s,  37.94k/sec]

Database file created.
Creating HTML report. Please wait.

HTML report completed.

Please open "./out/index.html"
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Perfect! Thanks so much! This makes the binary release process much easier!

**Pull request merged**
