### PR TITLE
chg: Replace httpclient with Puppy

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Related  #30
- Changed `httpclient` library to `Puppy`
   -  to reduce extra DLLs for windows

I would appreciate it if you could review when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### Environment1
- OS: macOS montery version 13.1
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8
```
% nim -v
Nim Compiler Version 2.0.0 [MacOSX: amd64]
% nimble -v
nimble v0.14.2 compiled at 2023-08-19 16:19:52
```
### Test
compiles successfully.
```
% nimble build -d:release
  Verifying dependencies for takajo@2.0.0
     Info:  Dependency on cligen@>= 1.5 already satisfied
  Verifying dependencies for cligen@1.6.14
     Info:  Dependency on suru@#f6f1e607c585b2bc2f71309996643f0555ff6349 already satisfied
  Verifying dependencies for suru@0.3.1
     Info:  Dependency on puppy@>= 2.1.0 already satisfied
  Verifying dependencies for puppy@2.1.0
     Info:  Dependency on libcurl@>= 1.0.0 already satisfied
  Verifying dependencies for libcurl@1.0.0
     Info:  Dependency on zippy@>= 0.10.0 already satisfied
  Verifying dependencies for zippy@0.10.10
     Info:  Dependency on webby@>= 0.1.6 already satisfied
  Verifying dependencies for webby@0.1.9
   Building takajo/takajo using c backend
fukusuke@fukusukenoMacBook-Air takajo % nimble build -d:release
  Verifying dependencies for takajo@2.1.0-dev
     Info:  Dependency on cligen@>= 1.5 already satisfied
  Verifying dependencies for cligen@1.6.14
     Info:  Dependency on suru@#f6f1e607c585b2bc2f71309996643f0555ff6349 already satisfied
  Verifying dependencies for suru@0.3.1
     Info:  Dependency on puppy@>= 2.1.0 already satisfied
  Verifying dependencies for puppy@2.1.0
     Info:  Dependency on libcurl@>= 1.0.0 already satisfied
  Verifying dependencies for libcurl@1.0.0
     Info:  Dependency on zippy@>= 0.10.0 already satisfied
  Verifying dependencies for zippy@0.10.10
     Info:  Dependency on webby@>= 0.1.6 already satisfied
  Verifying dependencies for webby@0.1.9
   Building takajo/takajo using c backend
```

**Comment by fukusuket** [comment]
### Environment2
- OS: Ubuntu 22.04 LTS
- Hard: Memory 8GB, Core 8
```
$ nim -v
Nim Compiler Version 2.0.0 [Linux: amd64]
$ nimble -v
nimble v0.14.2 compiled at 2023-08-01 01:21:33
```
### Test
```
```

**Comment by fukusuket** [comment]
### Environment2
- OS: Windows10
- Hard: Memory 8GB, Core 8
```
$ nim -v
Nim Compiler Version 2.0.0 [Linux: amd64]
$ nimble -v
nimble v0.14.2 compiled at 2023-08-01 01:21:33
```
### Test
```
```

```
PS C:\Users\fukus\takajo> .\takajo.exe vt-domain-lookup -a xxx --domainList .\t-domain.txt -o r-domain.csv --jsonOutput r-j-domain.json
...
Loaded domains: 10
Rate limit per minute: 4

Estimated time: 0 hours, 2 minutes, 30 seconds

 20%|█████                    |  2/10 [16.0s<01:42,  78.02m/sec]
Found malicious domain: creative-serving.com (Malicious count: 1 )
100%|█████████████████████████| 10/10 [02:34< 0.0s,  64.56m/sec]

Finished querying domains
Malicious domains found: 1
Saved CSV results to r-domain.csv (0 Bytes)
Saved JSON responses to r-j-domain.json (225.07 KB)

Elapsed time: 0 hours, 2 minutes, 35 seconds

PS C:\Users\fukus\takajo> .\takajo.exe vt-ip-lookup -a xxx --ipList .\t-ip.txt -o r-ip.csv --jsonOutput r-j-ip.json
...
Loaded IP addresses: 10
Rate limit per minute: 4

Estimated time: 0 hours, 2 minutes, 30 seconds

100%|█████████████████████████| 10/10 [02:36< 0.0s,  63.99m/sec]

Finished querying IP addresses
Malicious IP addresses found: 0
Saved CSV results to r-ip.csv (0 Bytes)
Saved JSON responses to r-j-ip.json (213.26 KB)

Elapsed time: 0 hours, 2 minutes, 36 seconds

PS C:\Users\fukus\takajo> .\takajo.exe vt-hash-lookup -a xxx --hashList .\t-hash.txt -o r-hash.csv --jsonOutput r-j-hash.json
...
Loaded hashes: 10
Rate limit per minute: 4

Estimated time: 0 hours, 2 minutes, 30 seconds

 30%|███████▌                 |  3/10 [31.4s<01:48,  64.53m/sec]
Found malicious hash: EEF166BAFB57343E7EFFC220FB70593573C98F365C3BD0B88E7CC1039C281684 (Malicious count: 1 )
100%|█████████████████████████| 10/10 [02:35< 0.0s,  64.85m/sec]

Finished querying hashes
Malicious hashes found: 1
Saved CSV results to r-hash.csv (0 Bytes)
Saved JSON responses to r-j-hash.json (610.31 KB)

Elapsed time: 0 hours, 2 minutes, 35 seconds
```

**Review by hitenkoku — APPROVED** [review]
@fukusuket thank you for your pull request.
LGTM.

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Sorry for the late review. LGTM!
Thanks so much!

**Pull request merged**
